### ISSUE TITLE
There is no index.js in the node_modules/angular-2-dropdown-multiselect

### ISSUE THREAD

**Issue by zfinxd** [softsimon/angular-2-dropdown-multiselect#101]
Hi  Simon,

I found an issue of this module exporting.
Mostly the standard way to export an module is having a file called index.js.
But in this module, only index.d.ts is found. 
Which causes that I should import it in this way
import { MultiselectDropdownModule } from 'angular-2-dropdown-multiselect/src/multiselect-dropdown';

or delete the config in my webpack.conf
      {
        test: /\.ts$/,
        exclude: /node_modules/,
        loaders: [
          'ts-loader'
        ]
      },
But I don't think it's good cause it's not standard way.

Thanks for you awesome multiselect! Which saves my time a lot.

**Comment by ermarkar** [comment]
Use

```
'angular-2-dropdown-multiselect': {
        main: 'src/multiselect-dropdown.js',
}
```

**Comment by softsimon** [comment]
I will publish the index.js in the next release tonight ;)
