### ISSUE TITLE
Error: (SystemJS) Can't resolve all parameters for MultiselectDropdown: (?, ?)

### ISSUE THREAD

**Issue by ermarkar** [softsimon/angular-2-dropdown-multiselect#102]
I was using angular-2-dropdown-multiselect of version 1.0.2. Everything was working fine. I updated this library from 1.0.2 to 1.0.3 and now this is showing

> Error: (SystemJS) Can't resolve all parameters for MultiselectDropdown: (?, ?).

**Comment by softsimon** [comment]
When using 1.0.4, it should be this for SystemJS:

`'angular-2-dropdown-multiselect': {
        main: 'index.js',
}`

`import { } from 'angular-2-dropdown-multiselect';`

**Comment by ermarkar** [comment]
Is there any issue with 1.0.3?
