### ISSUE TITLE
Input inside the dropdown has no name.

### ISSUE THREAD

**Issue by zfinxd** [softsimon/angular-2-dropdown-multiselect#103]
Hi Simon,

I am currently trying to put this multiselect into a form.
But get this error from angular2:

> EXCEPTION: Error in ./CustomizeFormComponent class CustomizeFormComponent - inline template:122:57 caused by: If ngModel is used within a form tag, either the name attribute must be set or the form
>       control must be defined as 'standalone' in ngModelOptions.
> 
>       Example 1: <input [(ngModel)]="person.firstName" name="first">
>       Example 2: <input [(ngModel)]="person.firstName" [ngModelOptions]="{standalone: true}">

I think the reason is the search bar inside the multiple select is an input but it has no name.

Here is my code
`<ss-multiselect-dropdown [settings]="mySettings" class="form-control"
          name="job" [options]="myOptions" [(ngModel)]="model.job"
          #job="ngModel" [ngModelOptions]="{standalone: true}">
        </ss-multiselect-dropdown>`

What is the correct way to use this multiple select within a form? 
Is it the only to use it within a form by using form-builder of angular?

Thanks very much.

**Comment by softsimon** [comment]
I believe it's your own <form tag that needs a name attribute, if you are using a form tag.

**Comment by zfinxd** [comment]
I've tried that. But it won't work. 😞

**Comment by softsimon** [comment]
Ok, you could be right. I'll add [ngModelOptions]="{standalone: true}" to the input.
