### ISSUE TITLE
Want to show customise data with json 

### ISSUE THREAD

**Issue by Anujmoglix** [softsimon/angular-2-dropdown-multiselect#105]
My json is not like dummy array .it doesn't have default array like name and id . It is as following :- 
  {
      "idModule": 1,"name": "PR","idClient": null,"displayName": "Purchase Request","createdAt": null,"updatedAt": null,"application": 1
    },
    {
      "idModule": 2,"name": "RFQ","idClient": null,"displayName": "Request For Quotation","createdAt": null,"updatedAt": null, "application": 1
    }

Now How to show  "displayName" and  get "idModule" after selection .

**Comment by nicholasguyett** [comment]
You'll have to map your source array into an array that matches the format this component expects.

For example,

```
this.displayData = srcData.map(item =>
  ({
    id: item.idModule,
    name: item.displayName
  })
);
```

**Comment by Anujmoglix** [comment]
Yes .i did the same thing previously , I just put one array push data into it.But thanks for the guidance ,

**Comment by siddharthaReddy** [comment]
I made few changes in [#72e77ca](https://github.com/siddharthaReddy/angular-2-dropdown-multiselect/pull/1/commits/72e77ca94b7c1940279aed1c9f3a9c5237915812) which will have the ability to pass the property you'd like to enable for checkbox selection.
