### ISSUE TITLE
use multiple drop-downs click aplyed  to all drop-downs

### ISSUE THREAD

**Issue by hazeem1991** [softsimon/angular-2-dropdown-multiselect#107]
`<div class="col-md-3 col-lg-3 col-sm-6">
        <ss-multiselect-dropdown 
            [options]="myProvincesOptions" 
            [settings]="mySettings" 
            [texts]="myTextsProvince" 
            (dropdownClose)="onChange($event,'province')"  
            [(ngModel)]="optionsProvincesModel">
        </ss-multiselect-dropdown>
    </div>
    <div class="col-md-3 col-lg-3 col-sm-6">
        <ss-multiselect-dropdown 
            [options]="mySectorsOptions" 
            [settings]="mySettings" 
            [texts]="myTextsSector" 
            (dropdownClose)="onChange($event,'sector')"  
            [(ngModel)]="optionsSectorsModel">
        </ss-multiselect-dropdown>
    </div>
    <div class="col-md-3 col-lg-3 col-sm-6">
        <ss-multiselect-dropdown 
            [options]="myCentersOptions" 
            [settings]="mySettings" 
            [texts]="myTextsCenter" 
            (dropdownClose)="onChange($event,'center')"  
            [(ngModel)]="optionsCentersModel">
        </ss-multiselect-dropdown>
    </div>
    <div class="col-md-3 col-lg-3 col-sm-6">
        <ss-multiselect-dropdown 
            [options]="myTeamsOptions" 
            [settings]="mySettings" 
            [texts]="myTextsTeam" 
            (dropdownClose)="onChange($event,'team')"  
            [(ngModel)]="optionsTeamsModel">
        </ss-multiselect-dropdown>
    </div>`
(dropdownClose)="onChange($event,'team')"   fired 4 times

**Comment by hazeem1991** [comment]
replace `@HostListener('document: click', ['$event.target'])`
with  `@HostListener('click', ['$event.target'])`

**Comment by softsimon** [comment]
@hazeem1991 Your suggested change doesn't work because without a document listener it will not close the dropdown when clicking outside.

**Comment by chris--jones** [comment]
Would this be solved by short-circuiting the click handler and returning immediately if the dropdown isn't visible?
e.g.
```typescript
@HostListener('document: click', ['$event.target'])
  onClick(target: HTMLElement) {
    if (!this.isVisible) return;
    let parentFound = false;
    while (target != null && !parentFound) {
      if (target === this.element.nativeElement) {
        parentFound = true;
      }
      target = target.parentElement;
    }
    if (!parentFound) {
      this.isVisible = false;
      this.dropdownClosed.emit();
    }
  }
```
