### ISSUE TITLE
onAdded and OnRemoved events

### ISSUE THREAD

**Issue by WardBeullens** [softsimon/angular-2-dropdown-multiselect#11]
First of all, thanks for the module!

It would be nice to have onAdded and onRemoved events that fires the id of an element when it is selected or unselected . 

Right now I maintain an extra copy of the list of selected id's to compare a new list of id's against each time an element is added/removed to find out which element has been added or removed. This is a bit of a nuisance.

**Comment by nicholasguyett** [comment]
What exactly is the use case for this?  I personally think diffing the old and new value is the outside the component is the correct way to approach this.

**Comment by sridharlatentview** [comment]
The use case could be i have  1 multi select drop down and i have one  select box. As i select from multi select, those items has to be removed from the other select box.
