### ISSUE TITLE
static title?

### ISSUE THREAD

**Issue by eagor** [softsimon/angular-2-dropdown-multiselect#112]
How do I make the button keep the same text, no matter if/how much items are selected?

**Comment by chris--jones** [comment]
You cannot presently, but it's an easy enough feature to add.

In **src\multiselect-dropdown.ts**

Add fixedTitle to IMultiSelectSettings 
```typescript
export interface IMultiSelectSettings {
...
  fixedTitle?: boolean;
```

and add the following logic to updateTitle:
```typescript
updateTitle() {
    if (this.numSelected === 0 || this.settings.fixedTitle) {
      this.title = this.texts.defaultTitle || '';
    }
```

Configure your title in the texts defaultTitle property as normal.

**Comment by eagor** [comment]
thank you for response. 
@softsimon would you consider merging such changes to master?

**Comment by softsimon** [comment]
@eagor Sure :)

**Comment by chris--jones** [comment]
I disagree with the setting being dynamicTitle as this is the default behaviour (default true), all other boolean settings are a default of false, which means their omission is implicit (undefined is falsey)

A better name would be fixedTitle or staticTitle as I suggested.

**Comment by softsimon** [comment]
Good point @chris--jones. I'll make that change before next version.
