### ISSUE TITLE
Is there a way to select dynamically?

### ISSUE THREAD

**Issue by pangky24** [softsimon/angular-2-dropdown-multiselect#118]
Is there a way to select dynamically?
I mean I want to select dynamically using code.

I check below issue, but there was no snippet.
https://github.com/softsimon/angular-2-dropdown-multiselect/issues/65 

please give me a guide ~~

**Comment by nicholasguyett** [comment]
Angular automatically syncs the ngModel value with the input's selection.  There's no snippet because all you have to do is have the value you want selected included in the value you use for ngModel.  Please refer to Angular's documentation for how ngModel works,

**Comment by pangky24** [comment]
@nicholasguyett 
sorry already I have studied, but I don't got it about your answer..

you just mean.. 
if I want to make selected status, just set the formConrolName's value, below?

**html**
`<ss-multiselect-dropdown` [options]="countryListOptions" formControlName="fltTrgtUsrCtr_"
`                                                     [settings]="pushSettings"></ss-multiselect-dropdown>`

**ts**
`this.form.controls["fltTrgtUsrCtr_"] = .... (array value?)`

**Comment by nicholasguyett** [comment]
See my answer on your new issue.  Also, its preferably to keep continued discussions on the same issue, rather than creating a new one.  I get notifications for your comments on closed issues as well as new ones.
