### ISSUE TITLE
Argument of type 'AbstractControl' is not assignable to parameter of type 'string'.

### ISSUE THREAD

**Issue by pangky24** [softsimon/angular-2-dropdown-multiselect#119]
- using..
angular2.4.0
angular-2-dropdown-multiselect": "1.0.5",

- code
  - code component ts
`this.form = this.formBuilder.group({
fltTrgtUsrCtr_: [''],
});`
`
this.form.controls['fltTrgtUsrCtr_'].setValue([]);
`

  - code html
`<ss-multiselect-dropdown [options]="countryListOptions" formControlName="fltTrgtUsrCtr_"                                                     [settings]="pushSettings"></ss-multiselect-dropdown>`

- get and set
`searchFilteredUserForm() {`
  `  let params: URLSearchParams = new URLSearchParams('', new CustomQueryEncoder());`
  `  params.set('fltTrgtUsrCtr_', this.form.controls['fltTrgtUsrCtr_']);`
`}`

**got an error below. (when I set the form.controls's value to params's set, got a error below.)**
`Argument of type 'AbstractControl' is not assignable to parameter of type 'string'.`

**console log**
![image](https://cloud.githubusercontent.com/assets/3896324/24689779/e37f3066-1a03-11e7-9996-ba85e0323d01.png)

I met this issue today's morning and had no problem until yesterday
how to get the form.controls value from ss-multiselect-dropdown

**Comment by pangky24** [comment]
'join' also is not working.
`this.form.controls['fltTrgtUsrCtr_'].join` 

`Property 'join' does not exist on type 'AbstractControl'.)`

**Comment by nicholasguyett** [comment]
This is not a problem with the component.  This issue tracker is for issues with the angular-2-dropdown-multiselect component, not for general angular2 issues.

The repository owner might know the answer, but you look up the documentation for angular2's form controls or ask your question or stackoverflow.  Those are more appropriate venues for your question and more likely to give you the answers you need.
