### ISSUE TITLE
Select all after entering text

### ISSUE THREAD

**Issue by TheAksh** [softsimon/angular-2-dropdown-multiselect#125]
When we filter the entries in the dropdown by entering some text and then do a 'Select All', all the entries in the original list get selected instead of only those that are shown in the filtered list.

**Comment by TheAksh** [comment]
any update on this bug? Is it being worked on currently ?

**Comment by chris--jones** [comment]
Yeah, I've got a fix ready; will submit a PR soon.

**Comment by TheAksh** [comment]
Im afraid to say that still all the entries get selected/deselected despite entering certain text in the filter.

**Comment by softsimon** [comment]
A new release with this fix has yet to be published to npm.

**Comment by TheAksh** [comment]
Being a newbie, I wanna ask how would I know if it has been published to npm with the latest changes?

**Comment by softsimon** [comment]
@TheAksh Sorry for the delay. It's published now. version 1.1.0

**Comment by TheAksh** [comment]
options may not exist on load in case of dynamic list population. Getting the error "TypeError: Cannot read property 'forEach' of undefined"

Might require reopening the issue

**Comment by TheAksh** [comment]
Any update on this?

**Comment by softsimon** [comment]
@TheAksh should be working in the latest release. v1.1.0
