### ISSUE TITLE
click checkbox issue for custom settings 

### ISSUE THREAD

**Issue by kthomas182** [softsimon/angular-2-dropdown-multiselect#129]
When I set:

selectionLimit: 1,
autoUnselect: true,

It is very buggy when you try to click on the actual check box. Sometimes it requires you to click the checkbox 2-3 times (the value in the dd list does change) because of the autoUnselect behavior. It seems to work fine when you just select the text.

To duplicate go here: https://chris--jones.github.io/angular-2-dropdown-multiselect/

Then just change the values to the above and you should be able to duplicate the issue.

Any ideas?

**Comment by chris--jones** [comment]
I'll have a look at it now, looks like the checkbox isn't correctly reflecting the state of the model.
