### ISSUE TITLE
CheckAll/UncheckAll option only works when clicking on the actual text, not on the list item.

### ISSUE THREAD

**Issue by dietergeerts** [softsimon/angular-2-dropdown-multiselect#137]
This should work just like the normal items, when you click on the list item, so next to the actual 'check all' text, then it also should do the check all function.

**Comment by chris--jones** [comment]
I cannot reproduce this, the click event is on the anchor, which will cover the width of the item:
![image](https://cloud.githubusercontent.com/assets/10459377/25075149/dcf3abae-2350-11e7-96c8-95d172b3a0db.png)
