### ISSUE TITLE
How to change button color

### ISSUE THREAD

**Issue by Ezeon** [softsimon/angular-2-dropdown-multiselect#140]
This might be a trivial issue, but how do I change the color of the button in the dropdown?

I've tried the following, but this approach does not work. The CSS class btn2 is not being applied in this case.

Settings:
mySettings: IMultiSelectSettings = {
buttonClasses: 'btn btn2',
};

CSS:
.btn2 {
	background-color: #ff0000;
}

**Comment by chris--jones** [comment]
That looks correct to me, is that the only configuration you are applying? If so the issue might be in the application of settings - are you assigning the settings properly on initialisation of the control?

You can see it working on my demo site here:
https://chris--jones.github.io/angular-2-dropdown-multiselect/
e.g. Change buttonClasses to btn btn-danger
```typescript
buttonClasses: 'btn bg-danger'
```

**Comment by Ezeon** [comment]
Thank you Chris. The example you gave did work. The issue seems to be that I can't apply css properties defined in the Angular 2 component css file. I guess this could be an issue with css scoping in Angular 2.

**Comment by Ezeon** [comment]
I found the issue. I was not properly applying the css to the child component. The following css works from the parent component:

:host /deep/ ss-multiselect-dropdown .btn2 {
  background-color: #ff0000;
}

**Comment by gangfang** [comment]
Hi @Ezeon, could you elaborate on your solution? I failed to understand that..

What is this:

> :host /deep/ ss-multiselect-dropdown

Thx!

**Comment by Ezeon** [comment]
@gangfang If you want to add scoped css in the parent component, you would need to use ':host /deep/' for it to affect a child component such as the ss-multiselect-dropdown.

Scoped css is called component styles in Angular. You can read about it here: https://angular.io/guide/component-styles

Of course, you could also just add it to the global css file.
