### ISSUE TITLE
Performing check all as the first action throws error

### ISSUE THREAD

**Issue by Arkkraa** [softsimon/angular-2-dropdown-multiselect#141]
### Expected Behavior
Selecting 'check all' as your first action on the dropdown selects all options

### Actual Behavior
Selecting 'check all' as your first action on the dropdown throws exception:
EXCEPTION: Error in ./MultiselectDropdown class MultiselectDropdown - inline template:18:10 caused by: Cannot read property 'indexOf' of undefined

### Proposal for fix
add this line to the begining of checkAll() function or in onChanges hook for options: if (!this.model) this.model = [];

**Comment by chris--jones** [comment]
Sounds like #116

Did you initialise your model property?

**Comment by Arkkraa** [comment]
Oh wow, i completely missed the ngModel..closing the issue. Thanks
