### ISSUE TITLE
Add empty value as option

### ISSUE THREAD

**Issue by innovaat** [softsimon/angular-2-dropdown-multiselect#145]
Is there an option or an easy way to add an empty value as option? Right now I am doing this, which works fine, but I wonder if there is a better way. If this is the easiest way, at least it is here for reference now :)

    this.api.get('users').subscribe((data) => {

        this.dataSelectOptions = data.map(
           r => ({ id: r.id, name: r.full_name })
        );

        this.dataSelectOptions.unshift({
            id:null, name: 'None'
        });
    });

**Comment by chris--jones** [comment]
That's pretty much how you do it.

You could do it in a one-liner using concat if you wanted (in case the unshift operation does not trigger change detection.)
e.g.
```typescript
this.api.get('users')
  .subscribe(data => this.dataSelectOptions = [{ id:null, name: 'None' }]
      .concat(data.map(r => ({ id: r.id, name: r.full_name })));
```
