### ISSUE TITLE
Select All and updating model feature/enhancement request

### ISSUE THREAD

**Issue by Arkkraa** [softsimon/angular-2-dropdown-multiselect#148]
Hi, I am running into an issue with the options model when using the check all functionality. When I select a single option, the options model is updated before the onAdded emit handler is called (which is what is expected). When selecting the "Select All" option, however, the emitter is called before the options model is updated and the options model doesn't reflect my selections. I was wondering if it could be possible to change it so that the model is updated before an emit occurs. Thanks!

### Possible Solution
Remove [line 382](https://github.com/softsimon/angular-2-dropdown-multiselect/blob/master/src/multiselect-dropdown.ts#L382) and add this.model.push(option.id) at [line 377](https://github.com/softsimon/angular-2-dropdown-multiselect/blob/master/src/multiselect-dropdown.ts#L377)

**Comment by chris--jones** [comment]
Issue is no longer present in latest release.
