### ISSUE TITLE
if with default selected when init, the is a bugs while select others

### ISSUE THREAD

**Issue by denghuiquan** [softsimon/angular-2-dropdown-multiselect#149]
As below image show:
![image](https://cloud.githubusercontent.com/assets/5303970/25518214/762a76ae-2c25-11e7-8e54-8dfc5a648c34.png)

**Comment by PlantPorridge** [comment]
@denghuiquan I'd suggest trying to replicate the bug using the latest code. Unfortunately the demo doesn't appear to be running the latest code so will contain fixed issues.

**Comment by chris--jones** [comment]
We'll need more details on how to reproduce, or we'll have to close this one.

**Comment by denghuiquan** [comment]
![image](https://cloud.githubusercontent.com/assets/5303970/26041468/a26ef02c-395f-11e7-9257-7747a97222d6.png)

**Comment by denghuiquan** [comment]
this is how to reproduce, and relative to one selected but title tell none selected.

**Comment by chris--jones** [comment]
I can only reproduce this on the old demo, not on mine which is newer (but still outdated)
https://chris--jones.github.io/angular-2-dropdown-multiselect/

**Comment by denghuiquan** [comment]
ok, i don't not your newer demo link before, thanks, i can't reproduce  that as well, sorry for bother you.
BTW, your new one looks nice jobs, thanks.
