### ISSUE TITLE
shall the ngModel type update: number[] => string[]

### ISSUE THREAD

**Issue by denghuiquan** [softsimon/angular-2-dropdown-multiselect#150]

**Comment by chris--jones** [comment]
I'm going to assume you're referring to this:
```typescript
model: number[];
```

It should be an array of any[] to match the id (also of type any)

**Comment by denghuiquan** [comment]
yes, it may be type any, but this must be able the give the custom filter or mapping function to deal with the difference between options and model display. BTW,, thank u for your patience and your nice plugin project.

**Comment by chris--jones** [comment]
Fixed with merge of #156
