### ISSUE TITLE
: Can't bind to 'ngModel'

### ISSUE THREAD

**Issue by chungtinhlakho** [softsimon/angular-2-dropdown-multiselect#152]
I'm trying to just replicate the example based on the read me and I get this.     My sharedModule imported the formModule and export it.  what am i missing?

`Error: Template parse errors: Can't bind to 'ngModel' since it isn't a known property of 'ss-multiselect-dropdown'. 1. If 'ss-multiselect-dropdown' is an Angular component and it has 'ngModel' input, then verify that it is part of this module. 2. If 'ss-multiselect-dropdown' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("<ss-multiselect-dropdown [options]="myOptions" [ERROR ->][(ngModel)]="optionsModel" (ngModelChange)="onChange($event)"></ss-multiselect-dropdown>"): ng:///SharedModule/MultiSelectDD.html@1:0`

--share module.
```

import { NgModule }            from '@angular/core';
import { CommonModule }        from '@angular/common';
import { FormsModule }         from '@angular/forms';
import {HttpModule} from "@angular/http";
import {StandardChartResource} from './standardChartResource'
import { ChartModule } from 'angular2-highcharts';
import {ServiceBase} from './base.service';
import {ChartComponent} from './charts/chart'


import {SelectModule} from 'ng2-select';

import {ShopSelectOption} from './select/shop-select-option';

import { MultiselectDropdownModule } from 'angular-2-dropdown-multiselect';
import {MultiSelectDD} from './select/multi-select-dd'

@NgModule({
  imports:      [ CommonModule,HttpModule,
  ChartModule.forRoot(require('highcharts')),SelectModule,MultiselectDropdownModule ],
  declarations: [ ChartComponent,ShopSelectOption,MultiSelectDD ],
  exports:      [ ChartComponent,ShopSelectOption,MultiSelectDD,
                  CommonModule, FormsModule,HttpModule,SelectModule,MultiselectDropdownModule ]
    ,providers: [ServiceBase,StandardChartResource]
})
export class SharedModule { }
```

**Comment by softsimon** [comment]
Try importing MultiselectDropdownModule in the actual module where you use the component in a template.

**Comment by chungtinhlakho** [comment]
no luck, tried everything.

**Comment by anilkganhari** [comment]
even i am facing the same issue

**Comment by chris--jones** [comment]
Not sure what best practice is, but I have the references in my declarations section:
e.g.

```typescript
import { NgModule }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule } from '@angular/forms';
import { AppComponent } from './app.component';
import { MultiselectDropdown } from './multiselect-dropdown';

@NgModule({
  imports:      [ BrowserModule, FormsModule ],
  declarations: [ AppComponent, MultiselectDropdown ],
  bootstrap:    [ AppComponent ]
})
export class AppModule { }
```

**Comment by jackyshuoyang** [comment]
yes, I have the same problem

**Comment by mihaistanescu** [comment]
I had this issue also, what fixed it for me was adding the FormsModule.

**Comment by softsimon** [comment]
FormsModule must be added to the same NgModule where the dropdown component is present.
