### ISSUE TITLE
Error while compiling with NGC

### ISSUE THREAD

**Issue by gund** [softsimon/angular-2-dropdown-multiselect#154]
Hi! First of all thanks for an awesome component!

It worked fine until I compiled my project with NGC and got next error:
```bash
Error: ENOENT: no such file or directory, open '/Users/.../node_modu
les/angular-2-dropdown-multiselect/src/multiselect-dropdown.metadata.json'
```

I checked that folder and also could not find any *.metadata.json files there. They just do not exist in the module...

Version of your lib I'm using is: v1.1.0

Can you please help how to resolve the problem, 'cause I saw you have merged before PR related for it but still...

Thanks

**Comment by gund** [comment]
PR #155 will fix this issue (I verified on my temporary package based on that PR).

**Comment by softsimon** [comment]
Merged and published.
