### ISSUE TITLE
Please be careful with versioning

### ISSUE THREAD

**Issue by warmans** [softsimon/angular-2-dropdown-multiselect#157]
Firstly thanks for your work on this component. It's one of the best multi-selects for angular 2+.

I would just like to ask for a bit of care with versioning. The most recent version updates the minor release (1.1.x -> 1.2.x) with a breaking change (directory structure changes). I think a lot of people allow minor updates in their package.json `^1.0.0` since this should only introduce non-breaking changes according to semver. A breaking change should increment the major version to prevent unexpected build breakages (particular under CI). 
I know semver can be a bit unclear and maybe someone would argue that without a breaking change in the API the major release number shouldn't change but I think re-arranging the directory structure counts as a breaking change as it will almost certainly affect client code (imports).

Thanks again.

**Comment by gund** [comment]
I would like to suggest moving to automated releasing with versioning using [semantic-release](https://github.com/semantic-release/semantic-release).

I personally using this method for quite long time and can tell that it is proven to be very reliable.
The main point there is to correctly make commit messages and based on them the tool will figure out new version and make a release.

If you are fine with this I can work on a PR to integrate it.
But to be more confident it is also a good idea to write a unit tests so before actual publishing the tests will ensure that library is in working state.

What do you think?

**Comment by softsimon** [comment]
I'm also considering moving this to a new project called something like . ngx-dropdown-multiselect

**Comment by gund** [comment]
@softsimon yes that would make sense as angular is progressing quite fast =)

**Comment by warmans** [comment]
Makes sense. Anyway I might as well close this since there isn't really anything to do. :+1:

**Comment by gund** [comment]
Btw @warmans in your original post regarding the change of the internal directory structure it usually should not affect final devs unless public API export location have changed because you always import stuff from the top level of the library.
