### ISSUE TITLE
btn-block style is not applied on the component after latest update

### ISSUE THREAD

**Issue by zzakir** [softsimon/angular-2-dropdown-multiselect#158]
After updating to version 1.2.0 'btn-block' style class is not applied after using it in settings.  
My setting config is:

multiSelectSettings: IMultiSelectSettings = {
        checkedStyle: 'fontawesome',
        buttonClasses: 'btn btn-default btn-block',
        showCheckAll: true,
        showUncheckAll: true,
        dynamicTitleMaxItems: 3,
        displayAllSelectedText: true
    };

Have a look at the below images:

Version 1.1.0
<img width="586" alt="screen shot 2017-05-04 at 9 51 22 am" src="https://cloud.githubusercontent.com/assets/5466170/25690543/f0c81be4-30af-11e7-9dbf-eff468460843.png">

Version 1.2.0
<img width="574" alt="screen shot 2017-05-04 at 9 52 55 am" src="https://cloud.githubusercontent.com/assets/5466170/25690547/fd4fe086-30af-11e7-8ef7-ef07c7096f3e.png">

**Comment by SherjeelSikander** [comment]
This solved a similar issue for me

multiSelectSettings: IMultiSelectSettings = {
checkedStyle: 'fontawesome',
buttonClasses: 'btn btn-default btn-block',
showCheckAll: true,
showUncheckAll: true,
dynamicTitleMaxItems: 3,
displayAllSelectedText: true,
**containerClasses: 'full-width'**
};

where

`.full-width{
    width: 100%;
}`

**Comment by chris--jones** [comment]
This is due to a change to display the control as inline-block by default as too many users were reporting that the control didn't close when clicking to the sides (as this was filled by the container).

Simply overriding **containerClasses** in config with anything should be sufficient to prevent the default dropdown-inline class from being applied.

**Comment by zzakir** [comment]
Thanks @chris--jones @SherjeelSikander
