### ISSUE TITLE
It's not working with angular2 version 2.4.7

### ISSUE THREAD

**Issue by musabbinkhalid** [softsimon/angular-2-dropdown-multiselect#168]
Hello all,
I tried downloading your module into my application, but it's not working, I'm new to angular2 development. Please help me how to get this done. 

any help would be appreciated.
Thanks
MK

**Comment by softsimon** [comment]
Angular4.x is required

**Comment by musabbinkhalid** [comment]
Yes !! but is there any other way to get it done ? because it's hard for me to upgrade my application to angular 4.X

**Comment by fabiantrejomx** [comment]
Is there some other way to make it work with angular 2?

**Comment by chris--jones** [comment]
You can replace the <ng-template> with <template> unfortunately this was a breaking change with Angular 4.0.

**Comment by softsimon** [comment]
Why can't people just upgrade to 4.x. It's the latest version, and is in my opinion it's a rather small version bump that shouldn't cause any major breaking changes for most projects :)

**Comment by musabbinkhalid** [comment]
Well I think, I need to change my requirements or build same component my self.  :-)

**Comment by sportity** [comment]
> Why can't people just upgrade to 4.x
I've just upgraded and now a bunch of other plugins got broken, the whole app is a complete mess of errors now.

**Comment by swapsword** [comment]
I am also facing the same issue(ng-template) as I am using angular version 2.4.9. 
I am getting following error:
```
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("" (click)="!option.isLabel && setSelected($event, option)" [class.dropdown-header]="option.isLabel">[ERROR ->]<ng-template [ngIf]="option.isLabel">{{ option.name }}</ng-template><a *ngIf="!option.isLabel" href=""): MultiselectDropdown@0:2214
Error: Template parse errors:
```

**Comment by softsimon** [comment]
Only way is to fork and replace <ng-template with <template and possibly some other 4.x breaking change.
