### ISSUE TITLE
Fit multiselect to parent container.

### ISSUE THREAD

**Issue by DarioN1** [softsimon/angular-2-dropdown-multiselect#169]
Hi, I need to fit the multiselect component width to its parent container, like bootstrap does with forms inputs text or basi select object...

I think that I just need to put "width:100%" somewhere or use a bootstrap class.... 

How can I do it?

Thanks to support

**Comment by chris--jones** [comment]
If you override container class (to anything, even empty string should work) the container will fill the space.
Then add btn-block to the button classes.
