### ISSUE TITLE
Dynamic loading of entries in dropdown

### ISSUE THREAD

**Issue by TheAksh** [softsimon/angular-2-dropdown-multiselect#171]
"options" may not exist on init in case of dynamic list population.

This piece was of code was added in the version 1.1.0 which is causing the issue.

```
 this.options.forEach(option => {
     if(typeof(option.parentId)!=='undefined'&&this.parents.indexOf(option.parentId)<0) {
        this.parents.push(option.parentId);
      }
```

Getting the error "TypeError: Cannot read property 'forEach' of undefined"

**Comment by chris--jones** [comment]
Fixed with PR #159

https://github.com/softsimon/angular-2-dropdown-multiselect/pull/159/files#diff-917dc5100b2453b183eeba217a22e963R116
