### ISSUE TITLE
'ng-template' is not a known element:

### ISSUE THREAD

**Issue by flexkiran** [softsimon/angular-2-dropdown-multiselect#174]
I am getting following error
Unhandled Promise rejection: Template parse errors:
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("" (click)="!option.isLabel && setSelected($event, option)" [class.dropdown-header]="option.isLabel">[ERROR ->]<ng-template [ngIf]="option.isLabel">{{ option.name }}</ng-template><a *ngIf="!option.isLabel" href=""): MultiselectDropdown@0:2214 ; Zone: <root> ; Task: Promise.then ; Value:

**Comment by chris--jones** [comment]
This is a breaking change with angular 4, there's already an issue raised.

**Comment by chris--jones** [comment]
Please refer to #168 for updates.
