### ISSUE TITLE
Run the code in Visual Studio code

### ISSUE THREAD

**Issue by aryanisml** [softsimon/angular-2-dropdown-multiselect#177]
Hi I downloaded the code and want to run with visual studio code editor, downloaded the respective js file using npm install in respective repository. 

I am new in angular 2, wanted to know how we can run the mention code.

**Comment by nicholasguyett** [comment]
I'm not sure about VS in specific, but usually with Angular, you run your build script if you're using typescript or AOT and then just open the html page that loads the angular code.

If you're new to Angular, I recommend checking out [Angular's "Getting Started" documentation](https://angular.io/docs/ts/latest/quickstart.html) to see how to run angular 2 code.  There's nothing specific to this component aside from what's in the readme.  For more general angular questions and concerns, I'd look at the link I gave you above in addition to googling some tutorials for Angular 2 or just following the examples and documentation on their docs website.
