### ISSUE TITLE
How to reset 'ss-multiselect-dropdown'

### ISSUE THREAD

**Issue by omgrace** [softsimon/angular-2-dropdown-multiselect#179]
I want to reset this control when clicked on Reset Button of Form.

```
<form [formGroup]="myForm" (ngSubmit)=save()>
    <ss-multiselect-dropdown [options]="myOptions" formControlName="optionsModel"></ss-multiselect-dropdown>
    <button type="reset" class="btn btn-default">Reset</button>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
```

**Comment by chris--jones** [comment]
Do you mean reset the selections? 

Should be as simple as setting myOptions to an empty array.

**Comment by omgrace** [comment]
Thanks @chris--jones.

**Comment by pmadhavan** [comment]
For resetting the selections I set optionsModel to an empty array instead of myOptions which removes all the options.
