### ISSUE TITLE
optional autoclosing

### ISSUE THREAD

**Issue by ChrisDXC** [softsimon/angular-2-dropdown-multiselect#180]
Hi,

I have added a feature that allows auto-closing the dopdown when the mouse leaves its element. I find it quite useful as one does not have to click outside the component to force it to close the dropdown or am I missing something?
The changes are really minor. I wanted to publish a new branch, and push my changes into it, this way my whole team would eventually use the new release directly from GitHub.
However I can create a branch, and create a Pull Request.

Can you please advise how proceed? I can send or place those 3 files on a secure servers for whoever would like to review and have them publish into a new release.

Thank you

**Comment by softsimon** [comment]
Best is to create a branch and do a pull request.
It should be an optional setting defaulting to the current behaviour.

**Comment by ChrisDXC** [comment]
Hi Softsimon, thank you for your prompt follow-up. I thought about doing that but it appears I am not allow to create a branch, and I tried to publish the one I created in my local repository using GitHub Desktop but receive this error: "Authentication failed. You may not have permission to access the repository. Open options and verify that you're signed in with an account that has permission to access this repository." I am signed in. So I am not sure how to get it there to be reviewed.

My changes are very limited and indeed allow the feature to be used optionally (defaulted to false):
dropdown.component.html:
+  <ul **(mouseleave) ="onMouseLeave()"** *ngIf="isVisible" class="dropdown-menu" [class.pull-right]="settings.pullRight" [class.dropdown-menu-right]="settings.pullRight"
Then implemented a new boolean setting (autoClose) entry in IMultiSelectSettings and used it in the newly defined method in dropdown.component.ts:
  onMouseLeave() {
      if (this.settings.autoClose) {
          this.toggleDropdown();
      }
I have attached the 3 modified files. I do not mind if someone else publish them in my place, I just would like my team to then pull a new version of the code with this feature included.

Thank you.

[dropdown.zip](https://github.com/softsimon/angular-2-dropdown-multiselect/files/1011086/dropdown.zip)

**Comment by nicholasguyett** [comment]
Hi @ChrisDXC.  You create the branch under your own account and use the "create pull request" button on the website.  It will register the pull request in this project where it can be reviewed and potentially accepted into the source.

The same process will work for any other open source project on github.

**Comment by chris--jones** [comment]
@ChrisDXC As an aside, if you want to customise packages for local development you can always use something like [sinopia](https://www.npmjs.com/package/sinopia) to create your own local packages or override existing packages for your team.
Even if your changes for this project are accepted, you'll have to await the next release.

**Comment by christianbrubaker** [comment]
Would you share the bits you changed please?  I need this exact same functionality
