### ISSUE TITLE
How can I use it If I do not have NgModule?

### ISSUE THREAD

**Issue by simoazzo** [softsimon/angular-2-dropdown-multiselect#181]
My Question is simple,
How can I use it If I do not have NgModule?

I do not have ngModule and at this stage I cannot update my Angular 2.

any Suggestion?
Thank you in advance

**Comment by softsimon** [comment]
So you're not even on 2.0 final? Then I guess you can't use it without manually extracting the code and put it into your project, remove the stuff that's "new" like ngModule and <ng-template

**Comment by simoazzo** [comment]
Maybe you can guide me please how I do that please?

Thank you.

Kind Regards

**Comment by simoazzo** [comment]
Or do you know of another package that it is not using the ngModule and I can use it?
Thanks

**Comment by nicholasguyett** [comment]
NgModule is an integral part of Angular >=2

If you find anything not using it, then its probably not maintained.
