### ISSUE TITLE
The dropdown is not closing when clicked outside.

### ISSUE THREAD

**Issue by sarojcobi** [softsimon/angular-2-dropdown-multiselect#184]
I have used the code like this, the drop down is not closing when I clicked outside of the div.

`<div class="dropdown"><ss-multiselect-dropdown [options]="multiSelectOptions" [(ngModel)]="selectedOptions" [texts]="multiSelectTexts" [settings]="multiSelectSettings"
						 (ngModelChange)="onChangeMultiSelect()" [class.no-dropdown]="!multiSelectOptions.length"></ss-multiselect-dropdown></div>`

**Comment by omgrace** [comment]
I have fixed this in our project.

You can do it in two ways:

1. Either set `.dropdown: inline-block;`
2. OR else make `button.dropdown-toggle: width: 100%;`

**Comment by chris--jones** [comment]
The dropdown should be inline-block by default in the latest release due to the `dropdown-inline` class against `containerClasses`.

If you add `btn-block` to your buttonClasses you can validate the width of the control is as expected.

**Comment by chris--jones** [comment]
Close due to inactivity, hope the suggestions resolved your issue 😄
