### ISSUE TITLE
Is there a way to add a new button in the dropdown menu

### ISSUE THREAD

**Issue by xiaohong3** [softsimon/angular-2-dropdown-multiselect#185]
I need to add a button in the check-control (Select/Unselect) section to allow adding new options dynamically. I am wondering if there is a way to do so or the only way is using JS to inject my button after the dropdown module is inited.

Thank you in advance.

**Comment by chris--jones** [comment]
There is no way to easily add a custom button, but you could try creating a dummy item in your list and watch the change event to adjust your list accordingly.
