### ISSUE TITLE
Disable options

### ISSUE THREAD

**Issue by elmugrat** [softsimon/angular-2-dropdown-multiselect#186]
It would be convenient to be able to selectively disable options via a property of `IMultiSelectOption`.  It should be fairly easy to implement with a small change to `setSelected` and `preventCheckboxCheck`

Any chance of this getting implemented?

**Comment by mrbgit** [comment]
+1

**Comment by mageshbala90** [comment]
I am also looking for this feature to be implemented.  Thanks in advance.

**Comment by lesliesu** [comment]
I am also looking for this feature to be implemented.  Thanks in advance.

**Comment by lisacopeland** [comment]
+1

**Comment by ericmschow** [comment]
I would love to see this as a feature.

**Comment by KevCJones** [comment]
Hopefully they like it, test it and we can get it merged sooner rather than later.  In the mean time i left instructions on how you can use my own take on it via the pull request.
