### ISSUE TITLE
Setting default value for different multiselect generated in an ngFor loop

### ISSUE THREAD

**Issue by DarioN1** [softsimon/angular-2-dropdown-multiselect#187]
Hi, I have a component that renders several multiselect inside a form.

The multiselect are generated by an ngFor loop.

All works properly for an initial form where the values are empty.

What I need to do is loading the default values on each multiselect.

How can I do it ?

this is the html code:
```
<tr *ngFor="let p of offert.Products">
....
<ss-multiselect-dropdown [options]="mul_Products" [texts]="myTexts" [settings]="mySettings" [(ngModel)]="p.listP"
                [ngModelOptions]="{standalone: true}"></ss-multiselect-dropdown>
....
</tr>
```

I tried to push the "p.listP" value in this way but it doesn't work:

```
for (let p of this.offert.Products) {
            var tmp:string[] = [];
            tmp.push(p.idProduct.toString());
            p.listP = tmp;
          }
```

Thanks to support

**Comment by nicholasguyett** [comment]
In Angular, you set your default values by setting the model the input is attached to.

So, in your instance, you should be setting your default values when you construct your offert.Products array.  Your initialization looks right to me.  Is the `id` value of your options the same as they value you're pushing into your array?  This component compares the `id` value of each `option` to the model array to determine if a value is selected; if they don't match, then it won't mark it selected.

On a side note, you should be able to rewrite your initialization more neatly as

```javascript
          for (let p of this.offert.Products) {
            p.listP = [p.idProduct.toString()];
          }
```

Double check to make sure you're matching your the `id` value in your options with the value you're pushing into the model array and let me know if that resolves your problem.

**Comment by DarioN1** [comment]
Hi nicholas and thanks to support!

In this moment I'm pushing this to the options:

```
for (let itm of this.listProducts) {
          let tmp: IMultiSelectOption = { id: itm.idProduct, name: "(" + itm.code + ") " + itm.product };
          this.mul_Products.push(tmp);
        }   
```

So I'm a bit confused...

**Comment by nicholasguyett** [comment]
Ah, I see a potential problem.  In the initialization code you included above, you're calling `toString()` but not in the options declaration.  I don't know with certainty at the moment, but I'd expect that using a `number` in the options and a `string` in your model would result in them not matching.  I recommend normalizing your ids to either all use the `number` type or all use the `string` type.  So, either do `id: item.idProduct` and `p.listP = [p.idProduct]` **OR** `id: item.idProduct.toString()` and `p.listP = [p.idProduct]`.

The reason being that `'1' === 1` will result in a `false` value, so they won't map to the same thing.  Please confirm that that that resolves your problem.

**Comment by DarioN1** [comment]
NICHOLAS YOU ROCK !!!

That was the problem!

**I was passing different tipe of value ( string vs number )...**

You've made start my day very well...
