### ISSUE TITLE
Minimum Selected Items in MultiSelect Dropdown

### ISSUE THREAD

**Issue by DorShoval** [softsimon/angular-2-dropdown-multiselect#196]
is there a way to define a minimum number limit of selected items in the multi-select dropdown?

for example: 
If I have 3 Selected items in the dropdown - that the minimum number of items that can be selected are 1 - (so there is no way that the user unselect all the items)

**Comment by nicholasguyett** [comment]
There is not.  You can only set a maximum selection limit.  If you want to ensure the user selects at least one value, I'd add that as your own custom form validation logic.
