### ISSUE TITLE
Title is not updated when options come later

### ISSUE THREAD

**Issue by sharok** [softsimon/angular-2-dropdown-multiselect#197]
I have a situation when model value is existed, but options come a little later. In this case options are filled and values are selected, but title is empty:
```
<ss-multiselect-dropdown
        [options]="myOptions"
        [(ngModel)]="optionsModel">
</ss-multiselect-dropdown>

export class App { 
  optionsModel: number[] = []; 
  myOptions = [];
  constructor() { 
    this.optionsModel.push(1); // imitate that model has value. In my real scenario I have select input(another component) and when user select value I show details and there are several angular-2-dropdown-multiselect components, and make reuqest to get options for multiselect.
  }
  
  fillOptions() {
    Observable.of([
            { id: 1, name: 'Option 1' },
            { id: 2, name: 'Option 2' },
        ])
        .timeout(200)
        .subscribe((data) => {
          console.log(data);
           this.myOptions = data;
        })
   
  }
}
```

I have created [Plunkr](https://plnkr.co/edit/aWMToeQ3DEodzxBi9geg?p=preview) for you, so you can see what I mean. Click `Fill Options` first and check multiselect values.

**Comment by nicholasguyett** [comment]
Thank you very much for the plunkr.  Its a big help for reproducing the issue.

**Comment by sharok** [comment]
@gund Thanks for fixing the issue. @softsimon Could you push the changes to npm?

**Comment by will093** [comment]
@softsimon Also waiting for changes to be pushed to npm.

**Comment by softsimon** [comment]
@will093 done

**Comment by will093** [comment]
@softsimon I now have an issue where updateTitle() is being called before the component is initialized. I think I have fixed the problem, please see my pull request.
