### ISSUE TITLE
Typescript error: Property 'assign' does not exist on type 'ObjectConstructor' for Line 146 and Line 147

### ISSUE THREAD

**Issue by dasis** [softsimon/angular-2-dropdown-multiselect#2]
Line 146:         this.settings = Object.assign(this.defaultSettings, this.settings);
Line 147:         this.texts = Object.assign(this.defaultTexts, this.texts);

I added these lines to fix it on my end.
//Reference: https://github.com/Microsoft/TypeScript/issues/3889
interface ObjectCtor extends ObjectConstructor {
    assign(target: any, ...sources: any[]): any;
}
declare var Object: ObjectCtor;

Typescript Version: 1.0.3.0
Not sure if the latest typescript would've fixed my issue :)

**Comment by softsimon** [comment]
I think you need the es6 polyfill for this.

**Comment by nicholasguyett** [comment]
Object.assign does not exist in ES5, so you either need to

- include a polyfill in your project (such as core-js)
- *OR* configure your tsconfig to build for `ES6` or `ES2015` (this may require a new version of typescript, I'm not certain
- *OR* include a type typings reference for ES6 libraries (this is what I am using in my current project as I have one browser to support that does not support the full ES6 syntax, but does support Object.assign and other new features)
