### ISSUE TITLE
Can't import MultiselectDropdownModule in ngModule

### ISSUE THREAD

**Issue by rahuldev761** [softsimon/angular-2-dropdown-multiselect#20]
I am unable to import MultiselectDropdownModule in ngModule.
I install it in  npm through this 
` npm install angular2-dropdown-multiselect --save-dev` 
and unable to import using this 
`import {MultiselectDropdownModule} from "angular-2-dropdown-multiselect";`  or
 `import {MultiselectDropdownModule} from "angular-2-dropdown-multiselect/multiselect-dropdown";
`
I am using **angular 2.0.0**

**Comment by softsimon** [comment]
I published an updated version. try now.
