### ISSUE TITLE
Pre-select from list what has been added while editing content 

### ISSUE THREAD

**Issue by Procaseycash** [softsimon/angular-2-dropdown-multiselect#208]
I will like to know if there is a way i can pre-select what i have added during creation while editing.

**Comment by nicholasguyett** [comment]
I don't quite understand your question.  If you set the values you want directly in the model value (in the example in the readMe, you could do this by assigning a value to `optionsModel`) it will pre-select them right from the get-go.

What do you mean by "while editing content"?

**Comment by Procaseycash** [comment]
Ok, what I meant is that when i check a list of items I wanna save and after save operation, I want to edit those items and I want my initial selected items to be checked in the list of items I have in the angular-2-dropdown-multiselect . how can I achieve that and I hope you understand my point?

**Comment by Procaseycash** [comment]
I got it done. Thanks

**Comment by nicholasguyett** [comment]
Glad you resolved your problem.  Since your problem was solved, I'm going to close this issue.
