### ISSUE TITLE
isLabel item selection

### ISSUE THREAD

**Issue by dachev** [softsimon/angular-2-dropdown-multiselect#217]
Hello, is there a way to disable selection of certain items? I use `isLabel` to display groups. Problems is that labels seem to be selected and counted as regular items when checkAll is clicked.

Thanks!

**Comment by BhavinPatel04** [comment]
+1

I am facing the same issue. When all the items in a particular group is selected, Label is passed in selectedOptions array as a regular item.

**Comment by ChoeYoonSeop** [comment]
+1

**Comment by LaniMoo** [comment]
+1

**Comment by stefanlangerhebo** [comment]
+1
There should be an option to prevent labels from being added to the list of selected items. In addition labels should not count - "All selected" should be displayed if all non-label items have been selected.

**Comment by softsimon** [comment]
Published in v1.6.2
