### ISSUE TITLE
Undefined properties on settings and texts

### ISSUE THREAD

**Issue by killzoner** [softsimon/angular-2-dropdown-multiselect#221]
Hi.

I've recently occured a new error since the refacto that occured in 1.4.0:
-  "Cannot read property 'searchRenderLimit' of undefined"
 - "Cannot read property 'containerClasses' of undefined"

The bug is visible in this plunkr : https://plnkr.co/edit/JHviCleCT36Arq4MCZWo?p=preview
I suspect that it works fine when you define the use in a "Boostrap" component (tested fine), but not in a children declared component of the same module (use case of the plunkr)

Since then, we have 2 options :
- either write defined-check on each getter and template property ('return this.settings && ...' and 'ngClass="settings?.[myValue]"'
- define default values in the component constructor.

I chose the second option since it's not requiring lots of change, and the change is nevertheless handled by ZoneJS. Plus it will be future proof if we define other getter functions or use it in template bindings.

I suspect too that #218 would be a duplicate and enforce a weird behaviour, since "default" values are not the same as the expected defaults (defaultTexts, defaultSettings), so i'm not sure it's relevant to keep the codebase from this commit/merge request.

See my request as solution : #222

**Comment by killzoner** [comment]
Well, was the pull request automatically merged? Seemed really fast to me...

**Comment by softsimon** [comment]
Not automatically ;-) Just merged and published a new version onto NPM.

**Comment by killzoner** [comment]
Ok thanks for the reactivity then! What about #218 ? Keeping as it is?
