### ISSUE TITLE
Using Observables to get the data and show on screen 

### ISSUE THREAD

**Issue by AngularTx** [softsimon/angular-2-dropdown-multiselect#225]
Hi,

I have to get the data from server and show , do we have the options available in this package? 
Also I  would like to remove the top section which shows "Select"  and shows what is selected or how many are checked .  I need just the the search part . 

Is there an option how i can achieve this ?

**Comment by nicholasguyett** [comment]
If the "data" refers to the available options, then just use `[options]="myOptionsObservable$ | async"`.
If it refers to the selected values, just subscribe to the observables (don't forget to unsubscribe when the component is destroyed) and set the value of the model directly.

I'm not entirely sure what you want with the second part, but you could hide the label section using css.

**Comment by AngularTx** [comment]
i would like to hide the select and make the search visible.

**Comment by AngularTx** [comment]
Hi 

Sorry I was not able to get the solution working.

Do you have a code snippet?
