### ISSUE TITLE
How to get object of selected list item?

### ISSUE THREAD

**Issue by lakhvir1994** [softsimon/angular-2-dropdown-multiselect#236]
I am working on angular2 application and in angular-2-dropdown-multiselect when I select multiple items in select list it will return array  of ids but I want array of objects. Objects contains the complete value of that list item.

**Comment by Ezeon** [comment]
I don't believe this is possible.

I think the easiest solution would be to store the objects in a separate array and create a function to retrieve them based on id.

**Comment by nicholasguyett** [comment]
The correct way to handle this situation is to map the I'd array to your object array using a function as @Ezeon suggested
