### ISSUE TITLE
Nothing found in dropdown-list

### ISSUE THREAD

**Issue by sree526** [softsimon/angular-2-dropdown-multiselect#237]
Hi I am using this in angular 2. I tried the steps as you have mentioned but in the list it's showing as nothing found. Can you please help me out. Thanks

**Comment by softsimon** [comment]
Use version 1.4.2 as of now, until a fix for 1.5.x is out.

**Comment by sree526** [comment]
Please improve the documentation or give the demo in plnkr . Thanks.

**Comment by AlexViderman** [comment]
Is this supposed to be fixed in 1.5.2? It didn't seem like it was fixed so I had to revert to 1.4.2. 

Thanks.

**Comment by softsimon** [comment]
Fixed now in v1.5.2
