### ISSUE TITLE
NgModel did not select

### ISSUE THREAD

**Issue by TeodorKolev** [softsimon/angular-2-dropdown-multiselect#242]
NgModel did not auto select property from dropdown.
```
 public mySettings: IMultiSelectSettings = {
    selectionLimit: 1,
    autoUnselect: true,
    closeOnSelect: true
  };
private countries = [
		{ id: 1, name: 'Sweden' },
		{ id: 2, name: 'Norway' },
		{ id: 3, name: 'Denmark' },
		{ id: 4, name: 'Finland' },
	];
myObject.coutry = { id: 2, name: 'Norway' };
```
`
  <ss-multiselect-dropdown [options]="countries" [settings]="mySettings" [(ngModel)]="myObject.country" (ngModelChange)="onChange($event)"></ss-multiselect-dropdown>`

I get 
ERROR Error: Error trying to diff ''. Only arrays and iterables are allowed

**Comment by softsimon** [comment]
ngModel will not be an object in your countries array, it will be an number[] array of the "id" properties.

myobject.country = [2];
