### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by nicholasguyett** [softsimon/angular-2-dropdown-multiselect#247]
A handful of features have been merged into the component that have not been reflected in the documentation.  The README should reflect the current available feature set.

**Comment by nicholasguyett** [comment]
@softsimon I no longer have time to contribute to this project (as you might have noticed by the fact that I haven't done much besides occasionally answer easy issues).  Could you remove me from the maintainers of this repository?  I can't figure out how to do it myself.

**Comment by softsimon** [comment]
ok @nicholasguyett

**Comment by chris--jones** [comment]
I think the README is updated now.
