### ISSUE TITLE
Not working with dynamic options from DB

### ISSUE THREAD

**Issue by amitgaur208** [softsimon/angular-2-dropdown-multiselect#248]
Its working fine if we use static options initially, but when i tried to retrive options data from DB its not listing them.

 response.category.map(job_category => {
            this.categories.push({ id: job_category.id, name: job_category.title });
      })

**Comment by anandSep90** [comment]
I also facing same issue. How did you resolve it? Please respond.

**Comment by chris--jones** [comment]
Assuming this.categories was the model, adding elements wouldn't trigger change detection.
You can fix this by replace the model reference with a new array.
e.g. Use concat instead of push:
```
this.categories = this.categories.concat(response.category.map(job_category => ({ id: job_category.id, name: job_category.title })));
```
