### ISSUE TITLE
Checkbox still toggles when selection limit is set

### ISSUE THREAD

**Issue by ChaudhryAtif** [softsimon/angular-2-dropdown-multiselect#249]
In the last example of the [demo](http://softsimon.github.io/angular-2-dropdown-multiselect/#), you can't click on 4th label (because selection limit is 3). But when clicking directly on the 4th checkbox, it still toggles, even though the model doesn't change (expected behavior).

**Comment by chris--jones** [comment]
Demo is outdated, this has been fixed.
