### ISSUE TITLE
selectionLimit = 1 and checkboxes

### ISSUE THREAD

**Issue by uwekolsch** [softsimon/angular-2-dropdown-multiselect#25]
if you set selectionLimit to 1 and checkedStyle to 'checkboxes' you still can select multiple checkboxes even though the model gets only one value assigned. It's probably not what one want. I got  around this by adding another option to the checkedStyle entry:

    checkedStyle?: 'checkboxes' | 'glyphicon' | 'radio';

and in the template 

                        <input *ngIf="settings.checkedStyle == 'radio'" name="radioitem" type="radio" [checked]="isSelected(option)" />

and in setSelected

            if (this.settings.checkedStyle == 'radio') {
                this.model = [option.id];
            }

**Comment by chris--jones** [comment]
I've proposed an "auto unselect" option which would allow for single selections, and for multiple selections constrained to the selection limit by automatically unchecking the oldest selections #27

Keen on some feedback, I think it might go nicely with an alternate checkedStyle, as I suppose semantically checkboxes don't make sense for single selections.

**Comment by softsimon** [comment]
Merged pull request and created new release.
