### ISSUE TITLE
More than one multiselect dropdown in a page

### ISSUE THREAD

**Issue by shaildegoam** [softsimon/angular-2-dropdown-multiselect#251]
Hi,
I have more than one multiselect dropdowns in my page. How do I write title for each dropdown, I don't want the default title "Select", but instead the titles I write. 

One method could be that I will write "Settings", "Texts" and "Options" for each of the dropdowns and also write "defaultTitle" for each of them. That would be very tedious. 

How can I write "Settings", "Texts" only one time and write "defaultTitle" for each of them separately along with "Options"?.

**Comment by Ezeon** [comment]
This problem can be solved in so many ways. The best solution would depend a lot on how many lists you need and if you are reusing the same list multiple places in your application.

I can give you an example from one of my application which are reusing the same lists in many components. Here I've chosen to put each multiselect list in it's own angular component and created a separate helper class to get "Settings", "Texts" and such. The advantage of this solution is that it's easy to reuse the same list in multiple components and it also keeps your view components clean of unnecessary code.

The skeleton of each list component looks like this:

@Component({
  selector: 'app-multiselect-somelist',
  template: `
  <ss-multiselect-dropdown [options]="ms_options" [texts]="ms_texts" [settings]="ms_settings" [(ngModel)]="ms_model" (ngModelChange)="onChange($event)"></ss-multiselect-dropdown>
  `,
})
export class SomeListMultiselectComponent implements AfterViewInit {
  public ms_options: IMultiSelectOption[] = [];
  public ms_model: string[] = [];
  public ms_settings: IMultiSelectSettings = MultiselectConfig.getConfig();
  public ms_texts: IMultiSelectTexts = MultiselectConfig.getText();
}

**Comment by nicholasguyett** [comment]
If you want different settings for each dropdown, you'll need separate settings objects.

The simplest way you could do this is to make a "base" texts object with your shared settings, and then use that base to create a texts object with your desired title for each dropdown.

```typescript

const baseTexts: IMultiSelectTexts = {
    // Your shared settings here
}

this.dropdownTexts1 = Object.assign({}, baseTexts, { defaultTitle: "Dropdown 1" });
this.dropdownTexts2 = Object.assign({}, baseTexts, { defaultTitle: "Dropdown 2" });
this.dropdownTexts3 = Object.assign({}, baseTexts, { defaultTitle: "Dropdown 3" });

```
