### ISSUE TITLE
Bootstrap 3 drop-down styles issues in 1.5.3

### ISSUE THREAD

**Issue by AlexViderman** [softsimon/angular-2-dropdown-multiselect#253]
I upgraded from 1.5.2 to 1.5.3 and my dropdown styles got screwed up. I use ngx-bootstrap and I may have some additional global styles I personally applied to the dropdowns, I cant really tell whats causing it. If I go between 1.5.3 and 1.5.2 the problem goes away and comes back. Any ideas what it can be?

<img width="239" alt="multi-slect" src="https://user-images.githubusercontent.com/21067092/28987573-9ccff2d2-7920-11e7-9a80-5a2667b72442.png">

**Comment by softsimon** [comment]
Fixed now in 1.5.4.
