### ISSUE TITLE
[Feature Proposal] Search field inside the button toggle

### ISSUE THREAD

**Issue by gund** [softsimon/angular-2-dropdown-multiselect#254]
Hi, I'm planning to improve UX of the filtering and would like to ask if you will be interested to merge this feature later on? So here you go...

Currently when you enable filtering from settings the filter field appears inside the dropdown itself (above options) which is not ideal user experience because first of all even though there is an autofocus attribute it works only first time ever user opens a dropdown and secondly if you have large set of options and you scroll them - user will loose filter field from the view.

So what I want to do is basically add filtering right inside a button when user clicks on it and put focus there programmatically (as a bootstrap 3 AngularJS dropdown equivalent implements it basically).

If you would like to have this feature I have a question what is the better approach to implement it:
1. As a replacement of current filtering
2. Or as a configurable option to switch between current and new filtering options

What do you think?

**Comment by Hesesses** [comment]
I would love to use this library if it would support this!

Optimal would be somehting like here: https://angular-ui.github.io/ui-select/demo-multiple-selection.html

**Comment by gund** [comment]
Well the basic idea is the same however those chips of selected items would definitely complicate it =)
At least I wont to move the search field inside the button.

But the main question still remains the same - which approach should we take:
1. Completely replace current filtering solution with the new one
2. Add configuration option to switch between current and new.

@softsimon what are your thoughts?
