### ISSUE TITLE
How to bind a dynamic collection of objects?

### ISSUE THREAD

**Issue by sajeelmunir** [softsimon/angular-2-dropdown-multiselect#262]
Hi, 

How to bind a dynamic collection of objects (JSON) to a drop-down?

Hard coded example:
this.myOptions = [
            { id: 1, name: 'Option 1' },
            { id: 2, name: 'Option 2' },
        ];

JSON collection:
{
   id:1,
   country: USA,
}
{
   id:2,
   country: UK,
}
AND SO ON ....

Thanks in advance,

**Comment by nicholasguyett** [comment]
Just assign a new array to the myOptions property when there are updates and it will automatically update.
