### ISSUE TITLE
dropdownClosed($event) returns event as undefined

### ISSUE THREAD

**Issue by BhavinPatel04** [softsimon/angular-2-dropdown-multiselect#270]
Great product. Appreciate it. Thank You. :)

`<ss-multiselect-dropdown [options]="multiselectDropdownOptions"
          (dropdownClosed)="onFilterChange($event, 'multiSelect-dropdown')"
          [settings]="multiselectDropdownSettings"
          [texts]="dropdownTexts"
          [(ngModel)]="selectedOptions.multiselectDropdown" required>
      </ss-multiselect-dropdown>
`

` (dropdownClosed)` returns me $event as undefined 

> Note: Works fine if I use `(ngModelChange)`

**Comment by gund** [comment]
That is by design, events like `dropdownClosed` and `dropdownOpened` are just to notify you about event but do not send you any `$event` data.

**Comment by BhavinPatel04** [comment]
@gund, thank you for your response

I solved it using:

`<ss-multiselect-dropdown [options]="multiselectDropdownOptions" (dropdownClosed)="onFilterChange(selectedOptions.multiselectDropdown, 'multiSelect-dropdown')" [settings]="multiselectDropdownSettings" [texts]="dropdownTexts" [(ngModel)]="selectedOptions.multiselectDropdown" required> </ss-multiselect-dropdown>`
