### ISSUE TITLE
how to set default values oninit from json data value?

### ISSUE THREAD

**Issue by sajeelmunir** [softsimon/angular-2-dropdown-multiselect#282]
How to set the initial selected values onInit using Json data?

Json value: // String value
{
mySelection: '0,2,3' 
}
// Default selection Hard-coded
optionsModel: number[] = [1, 2]; // Works fine

// Binding Json value ['0,2,3' ]
this.optionsModel = [Number(mySelection)] // Only select the first one '0'

I should select all three items from the drop-down.

Someone please help me! Thank you for your help in advance.

**Comment by softsimon** [comment]
['0,2,3' ] doesn't work because it's a string of all numbers in the first field.
It must be [0,2,3].

You need to convert, and you could write something like:
`
this.optionsModel = mySelection.split(',').map((str) => parseInt(str, 10));
`
