### ISSUE TITLE
Search in "id" as well as "name"

### ISSUE THREAD

**Issue by PolarbearDK** [softsimon/angular-2-dropdown-multiselect#295]
I have a list of institutions where the name of the institution is not always unique.
The users often know the id of the institution, so I would like to allow the user to search in both name AND id fields. 

The search in "name" is hard coded within MultiSelectSearchFilter pipe (a bit of an odd construct as the pipe is provided by the component itself, but never used as a pipe).

Is there any way I can customize the search behavior to include id in search?
I would prefer if I could avoid appending the id to the name.

**Comment by gund** [comment]
You can easily extend from `MultiSelectSearchFilter` pipe to create your own and then just provide your custom one instead of original via NgModule `providers`.

**Comment by PolarbearDK** [comment]
I'm aware of that, but there is no extension points, so you basically have to copy all the code (for a pipe there is quite a lot). I don't like messing with the internals of a component, that later on might cause an incompatibility when upgrading.

I'm looking at the new lazy feature right now, as it might solve the problem.

**Comment by PolarbearDK** [comment]
I was able to solve this using lazy load feature.

**Comment by gund** [comment]
@PolarbearDK glad that you solved it.
Regarding my original proposal I did not mean to copy the whole internals, instead to extend it and call super inside the transform method.
You can make your search by id and then combine results with the super call results and get the outcome without ever caring about implementation details of the original pipe =)
