### ISSUE TITLE
Not emitting as object

### ISSUE THREAD

**Issue by kishore1106** [softsimon/angular-2-dropdown-multiselect#3]
what changes should i need such that it  emits entire object that i have selected and is there is no property to pre select an option by default?

**Comment by nicholasguyett** [comment]
I can't answert the first question, but for pre-selected options, in Angular 2 you are expected to set the default values into the property yourself.

So if your dropdown has `[(ngModel)]="myValues"` then you'd set `myValues = ["my", "default", "values"];` in your component, and those options should then be pre-selected in the dropdown.  This applies to all form controls in Angular2: defaults must be manually set.

**Comment by nicholasguyett** [comment]
As the only remaining question overlaps with #8, I'm going to close this in favor of the more focused issue.
