### ISSUE TITLE
1 selection

### ISSUE THREAD

**Issue by shay972** [softsimon/angular-2-dropdown-multiselect#30]
Is there a way to add 1 line selection without checkbox? (I wish to use your project for my entire web)
I tried to overcome by limit the selection to "1"
but there is a bug, you can select more than 1, and it will not select the your new selection and remove old selection

**Comment by softsimon** [comment]
This was also mentioned in #25. Is what you are looking for a radio-button list and not a checkbox list?

**Comment by shay972** [comment]
no checkbox (dropdown, that I can choose 1 line)

**Comment by shay972** [comment]
I added 1 line support: (none)

checkedStyle?: 'checkboxes' | 'glyphicon' | 'none' ;


  setSelected(event: Event, option: IMultiSelectOption) {
        if (!this.model) this.model = [];    
        var index = this.model.indexOf(option.id);
        if (index > -1) {
            this.model.splice(index, 1);
            console.log("removing");
        } else {
            if (this.settings.selectionLimit === 0 || this.model.length < this.settings.selectionLimit) {
                this.model.push(option.id);
                console.log("adding");
            } else {
                if (this.settings.autoUnselect) {
                    this.model.push(option.id)
                    this.model.shift();
                  } else {
                    if (this.settings.checkedStyle == "none"){
                        this.model.splice(index, 1);
                        this.model.push(option.id);
                          console.log("removing and adding");
                    } else{    
                      this.selectionLimitReached.emit(this.model.length);
                       return;
                    }
               }
            }
        }
        if (this.settings.closeOnSelect) {
            this.toggleDropdown();
        }
        this.onModelChange(this.model);
    }

**Comment by nicholasguyett** [comment]
Pull Request #27 looks like it should provide the functionality you want.

Please try the latest and see if it fits your needs.
