### ISSUE TITLE
Support Angular 5

### ISSUE THREAD

**Issue by inzerion** [softsimon/angular-2-dropdown-multiselect#306]
Hi softsimon, 

Please add support of Angular 5

**Comment by softsimon** [comment]
As soon as Angular 5.x reaches a stable release.

**Comment by seigneur** [comment]
Can we reopen this now?

**Comment by softsimon** [comment]
Can you point to what in the component that is incompatible with Angular5?

**Comment by seigneur** [comment]
Please close, I posted in the wrong module.

**Comment by andy-** [comment]
Now that Angular 5 has been released are you going to update ?
After migration i get this error: 
ERROR in ./node_modules/angular-2-dropdown-multiselect/src/multiselect-dropdown.ts
Module build failed: Error: C:\workspace\OPS\OPSTRAX\src\Opstrax\ux\opstrax\node_modules\angular-2-dropdown-multiselect\src\multiselect-dropdown.ts
 is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (C:\workspace\OPS\OPSTRAX\src\Opstrax\ux\opstrax\node_modules\@ngtools\webpack\src\angular_compiler_pl
ugin.js:629:23)
    at plugin.done.then (C:\workspace\OPS\OPSTRAX\src\Opstrax\ux\opstrax\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ ./src/app/shared/module/shared.module.ts 14:0-100
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

**Comment by inzerion** [comment]
13:02:59 [0m[91mnpm WARN[0m[91m angular-2-dropdown-multiselect@1.6.3 requires a peer of @angular/common@^4.0.0 but none was installed.
13:02:59 npm[0m[91m WARN[0m[91m angular-2-dropdown-multiselect@1.6.3 requires a peer of @angular/core@^4.0.0 but none was installed.
13:02:59 [0m[91mnpm WARN[0m[91m angular-2-dropdown-multiselect@1.6.3 requires a peer of @angular/forms@^4.0.0 but none was installed.

**Comment by carstenbaumhoegger** [comment]
hey @softsimon!

You released a new version 1.7 but the installation errors still occur.

Can you please update the targeted version in your `package.json`?

```
npm WARN angular-2-dropdown-multiselect@1.7.0 requires a peer of @angular/common@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-2-dropdown-multiselect@1.7.0 requires a peer of @angular/core@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-2-dropdown-multiselect@1.7.0 requires a peer of @angular/forms@^4.0.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by softsimon** [comment]
Fixed now in 1.7.1

**Comment by janbomber** [comment]
is it really a patch version ?

**Comment by carstenbaumhoegger** [comment]
thank you @softsimon !

**Comment by softsimon** [comment]
@janbomber 1.7 which was released just a day before has breaking changes with bootstrap4 support and angular5 support was suppose to come with it.
