### ISSUE TITLE
Very large data issue

### ISSUE THREAD

**Issue by sukhminderx** [softsimon/angular-2-dropdown-multiselect#318]
Hi

My data to be populated into options is an array with >80,000 objects. It takes like a minute to open the dropdown. The search and scroll is also very slow.
Do we have a way to increase the efficiency to the multiselect for very large data?

Thanks

**Comment by softsimon** [comment]
Have you tried using the Lazy Loading feature described in the Readme?

**Comment by sukhminderx** [comment]
Lazy loading worked perfectly. Thanks.
