### ISSUE TITLE
It looks like after last updates you lost updating select title

### ISSUE THREAD

**Issue by demo-igor** [softsimon/angular-2-dropdown-multiselect#321]
Hi. It looks like after last updates you lost updating select title.
After debug I see that `this.lazyLoadOptions` is empty. So in case `this.settings.isLazyLoad` is true select box title won't updated on set some data to `[options]`

https://github.com/softsimon/angular-2-dropdown-multiselect/blob/master/src/dropdown/dropdown.component.ts#L395

Easiest fix
`var useOptions = this.settings.isLazyLoad && this.lazyLoadOptions ? this.lazyLoadOptions : this.options;`

Instead: 
var useOptions = this.settings.isLazyLoad ? this.lazyLoadOptions : this.options;

Could you please check it?

**Comment by softsimon** [comment]
Published in v1.6.2
