### ISSUE TITLE
How to build and test locally

### ISSUE THREAD

**Issue by Hainesy** [softsimon/angular-2-dropdown-multiselect#325]
I was hoping to add some functionality via a pull request but really struggling getting this working locally. I've cloned and linked the repo and followed various online tutorials on how to do this but to no avail. Do you have a list of easily reproducible steps on how to get a local lib working in a local project for test purposes?

**Comment by thebf** [comment]
Potentially add something like the demo page to the source package so that a simple npm install+ng serve would render a testing page. It would allow for rapid prototyping without a large setup step.
I've seen quite a few components having a demo directory specifically for this purpose.

**Comment by chris--jones** [comment]
Added with #352
