### ISSUE TITLE
'text-dark' class not working

### ISSUE THREAD

**Issue by vehansayvazi** [softsimon/angular-2-dropdown-multiselect#327]
itemClasses:'text-dark' doesn't change the text color for me.

**Comment by shaychoo** [comment]
same with
itemClasses:'text-right'

**Comment by chris--jones** [comment]
The classes are applied to the label so they may not be compatible with the styling you require.
text-right, for example, won't work unless you also increase the width of the label with other CSS rules.

**Comment by vehansayvazi** [comment]
Thanks @chris--jones 

Would you please provide an example of how to use itemClasses? Haven't been able to find one yet.

**Comment by chris--jones** [comment]
They're best used with a custom css class as bootstrap doesn't have much in the way of label styling.

e.g.
```
label.custom {
    color: black;
    text-align: right;
    width: 100%;
}
```

and in your config
```
itemClasses:'custom'
```

**Comment by vehansayvazi** [comment]
Thanks!
