### ISSUE TITLE
Emulate single option select?

### ISSUE THREAD

**Issue by InigoWD** [softsimon/angular-2-dropdown-multiselect#33]
Is there an easy way to emulate just being able to select one option at a time? I have set the `selectionLimit:1`, and `closeOnSelect: true`, which works, but when selecting a different option, it forces you to first **deselect** whichever one is currently selected before you can select a new option.

Can I get around this so that clicking on a new (unselected) option automatically deselects other selected options in a single click (ie. standard single selection behaviour)?

**Comment by duduvp** [comment]
I also need it so much @InigoWD.. Look at #30. @shay972 has proposed an option to do this, but I didn't get success yet.

@softsimon can you help we please?

**Comment by InigoWD** [comment]
I have managed to hack this by resetting the `selectedOptions` array to an empty array whenever the dropdown is clicked. I also have to set a boolean value to ensure it's only the first click that triggers it, then prime it again using the `ngModelChange` event when an option is selected. Of course also set `selectionLimit:1` and `closeOnSelect:true` as above.

Certainly not ideal, but hey... Does seem like a bit of an oversight not to have a single selection mode built in.

**Comment by nicholasguyett** [comment]
Pull Request #27 looks like it should provide the functionality you want.

Please try the latest and see if it fits your needs.

@InigoWD, I would disagree that its an oversight for the project.  This component is a multiselect dropdown, but the behavior requested here is the behavior of a set of radio buttons.

**Comment by InigoWD** [comment]
#27 is exactly the solution, thank you!

Single selection mode is vital IMO, since I have a form of many selection inputs, some single-select, some multi-select, and I want them to all look and feel the same. Therefore it is much more convenient to use the same plugin for all of them. I expect this is why this request was so popular.

**Comment by nicholasguyett** [comment]
@InigoWD, thank you for the clarification.  I can see the consistency being a concern, even if it kind of clashes with the more semantic meaning of multiselect.
