### ISSUE TITLE
Issue with version published on NPM

### ISSUE THREAD

**Issue by bnormoyle** [softsimon/angular-2-dropdown-multiselect#330]
Hi,

The version of this library available on NPM has the following code as part of the dropdown template:
         ` <template [ngIf]="option.isLabel">
            {{ option.name }}
          </template>`

Causing errors now, as template is deprecated and ng-template is required. I see the code here uses ng-template for the element in question - does it need to be updated on npm? Thanks.

**Comment by softsimon** [comment]
The latest version published to NPM does not contain <template. It has been <ng-template for a while now.

**Comment by bnormoyle** [comment]
Weird! Don't know why the version I got was wrong then. Thanks for checking.
