### ISSUE TITLE
Duplicate values while filtering

### ISSUE THREAD

**Issue by harikrishnan-u01** [softsimon/angular-2-dropdown-multiselect#337]
Duplicate values are getting displayed while filtering the results.

Release: v1.6.2

![image](https://user-images.githubusercontent.com/10159959/33332415-3616cb70-d432-11e7-89a9-a85c581d9ab7.png)

![image](https://user-images.githubusercontent.com/10159959/33332426-3dc61f1a-d432-11e7-9358-46a7b5d8ea29.png)

Plnkr: https://plnkr.co/edit/4TLM3sLKHawfz3BJkM1W?p=preview

Kindly help in providing a fix/work around for this issue as this is a blocker for us.

Thanks,
Hari

**Comment by thebf** [comment]
I found a workaround:
settings
searchMaxLimit: 0,
searchMaxRenderedItems:5,

Seems to behave like your plunker setup just without the duplicate search results, will keep searching for the root cause.

**Comment by thebf** [comment]
@gund 
I've narrowed it down to searchMaxLimit: as the triggering factor I think it's some error in your search pipe code that was patched in 5 months ago.
Different values changes which values get duplicated in the result set
1300 is duplicated when the searchMaxLimit is set to 4-12 but when set to 3 or 13 it is not duplicated.
When set to 3 3700 is not duplicated while set to 13 it is duplicated.

This smells like a mathematical bug way above my skill level.

**Comment by harikrishnan-u01** [comment]
Hi @thebf 
Thank you for the quick responses.

In my project , I have the following settings for muti scan: 

multiSelectSettings: IMultiSelectSettings = {
      enableSearch: true,
      checkedStyle: 'fontawesome',
      searchRenderLimit: 30,
      searchRenderAfter: 1,
      searchMaxLimit: 30
  };
  // Text configuration
  multiSelectTexts: IMultiSelectTexts = {
      searchPlaceholder: 'Search...',
      searchEmptyResult: 'No results found!',
      defaultTitle: 'Fund List',
  };


I need the searchMaxLimit as 30 since the dataset I have has 5000 records.
Is there any other work around which I can use?

Thanks,
Hari

**Comment by gund** [comment]
Hey @thebf, thanks for pointing out for the cause.

It was quite crazy to nail down the root cause of the issue but long story short it turned out that each search pass was drifting the cache index (which is used to skip already searched area of the options list) and so on 3rd-4th letter you would start getting those dupes.

The fix now is in PR, but you guys can pull it and test out if you want =)

Cheers

**Comment by softsimon** [comment]
Now try with v1.6.3
