### ISSUE TITLE
Inconsistent (de)selecting behavior when filter is enabled

### ISSUE THREAD

**Issue by thecp** [softsimon/angular-2-dropdown-multiselect#347]
Selecting and deselecting behave differently when filter is enabled:

1. Search for something and click `deselect` -> ALL items get deselected
2. Search for something and click `select` -> only the filtered items get selected

I don't know when this came in but some weeks ago case 2 worked for both `select` and `deselect`. Also the question what is the _correct_ behavior. Should only the filtered items be selected and deselected or all items.

**Comment by chris--jones** [comment]
I think filtering should leave now hidden items in the state they were before filtering and only affect the visible items in the control.
