### ISSUE TITLE
On first display, the default title is ignored if selectedOptions is null

### ISSUE THREAD

**Issue by cpoissonnier** [softsimon/angular-2-dropdown-multiselect#36]
When the page is displayed and that nothing is selected, the default title is not displayed because no changes are detected : 

    ngDoCheck() {
        let changes = this.differ.diff(this.model);
        if (changes) {
            this.updateNumSelected();
            this.updateTitle();
        }
    }

**Comment by nicholasguyett** [comment]
I just tested with the latest and was unable to reproduce this.  Could you see if the issue still exists with the latest version?

**Comment by cpoissonnier** [comment]
My bad, we used an old version, it works perfectly now.

Thanks !
