### ISSUE TITLE
Can we pass HTML to IMultiSelectOption to modify the look of the name?

### ISSUE THREAD

**Issue by h0ujun** [softsimon/angular-2-dropdown-multiselect#371]
Can we pass HTML to IMultiSelectOption to modify the look of the name?
Thanks!

**Comment by chris--jones** [comment]
No, but we're looking at the possibility of templates for the next major release.

**Comment by h0ujun** [comment]
Thanks will wait for it!

**Comment by TheAksh** [comment]
Could you provide a guesstimate by when it would be available for use?
