### ISSUE TITLE
changelog version

### ISSUE THREAD

**Issue by sireneweb** [softsimon/angular-2-dropdown-multiselect#391]
Hi, do you have any changelog to see which differences between 1.6.3 and 1.7 ?

**Comment by softsimon** [comment]
https://github.com/softsimon/angular-2-dropdown-multiselect/releases/tag/v1.7

**Comment by sireneweb** [comment]
Thanks a lot :)

**Comment by sireneweb** [comment]
angular-2-dropdown-multiselect Versio 1.7 continues to work with Bootstrap 3.0 ?
