### ISSUE TITLE
Changes wont show-up in Production build.

### ISSUE THREAD

**Issue by saketthakare** [softsimon/angular-2-dropdown-multiselect#393]
I added few lines of code in `dropdown.component.js` file in version 1.3.2. I am able to see those changes in dev build but not in Prod Aot build.

Do I need to build the plugin again for these changes to show-up? If yes how to do that?

**Comment by ert78gb** [comment]
it is a typescript project don't change anything in js files, because the typescript compiler will override it in the build process

**Comment by saketthakare** [comment]
I built the corresponding metadata.json and it worked in AOT.

**Comment by ert78gb** [comment]
I don't understand you.

If you have a typescript file and when you compile it to javascript then the js file will override.
If you use npm when every `npm i` will override all files in the node_modules folder.

Could you describe your project structure and exactly what did you do?

**Comment by saketthakare** [comment]
I am not using `npm i` currently. I have the complete source including the node_modules folder.
