### ISSUE TITLE
Rxjs6 not compatible 

### ISSUE THREAD

**Issue by AlexKhymenko** [softsimon/angular-2-dropdown-multiselect#412]
Hi Thank You for the library. 
Are there any plans to support rxjs6 natively?

**Comment by martin-g** [comment]
I guess this actually means to support Angular 6.

**Comment by AlexKhymenko** [comment]
create pull request https://github.com/softsimon/angular-2-dropdown-multiselect/pull/413

**Comment by martin-g** [comment]
1.8.0 has been released today!
