### ISSUE TITLE
multi dropdown issues - not closed previous one if i click on another dropdown

### ISSUE THREAD

**Issue by mrpatel15** [softsimon/angular-2-dropdown-multiselect#420]
1. I have 6 diff..dropdown and i  need close open one if click on another dropdown. it seems not closing open dropdown. 
2. But if i click outside then it closed all dropdown.
3. Dropdown option content is overlapping through another dropdown
**pease see attached screenshot,** 

Can you help me to fix quickly.
<img width="964" alt="screen shot 2018-05-21 at 1 16 16 pm" src="https://user-images.githubusercontent.com/11543074/40322890-61fa7fa2-5cf9-11e8-8086-6b70a58f14dd.png">

`<ss-multiselect-dropdown #multiDropDownOne (mousedown)="clickedEvent()"
          [settings]="{dynamicTitleMaxItems: 0,  enableSearch: true, checkedStyle: 'fontawesome', showUncheckAll: true, closeOnSelect: true}"
          [texts]="{defaultTitle: 'DID', uncheckAll: 'Reset'}" [options]="did"
          [(ngModel)]="selectedDid" (ngModelChange)="onSelect()"></ss-multiselect-dropdown>

        <ss-multiselect-dropdown #multiDropDownTwo
          [settings]="{dynamicTitleMaxItems: 0, checkedStyle: 'fontawesome', showUncheckAll: true, closeOnSelect: true}"
          [texts]="{defaultTitle: 'DEPT NAME',uncheckAll: 'Reset'}" [options]="department_name"
          [(ngModel)]="selectedDeptName" (ngModelChange)="onSelect()"></ss-multiselect-dropdown>

    

        <ss-multiselect-dropdown #multiDropDownThree
          [settings]="{dynamicTitleMaxItems: 0, checkedStyle: 'fontawesome', showUncheckAll: true, closeOnSelect: true}"
          [texts]="{defaultTitle: 'GL Account', uncheckAll: 'Reset'}"
          [options]="account" [(ngModel)]="selected_GL_ACCOUNT" (ngModelChange)="onSelect()"></ss-multiselect-dropdown>

  

        <ss-multiselect-dropdown #multiDropDownFour
          [settings]="{dynamicTitleMaxItems: 0, checkedStyle: 'fontawesome', showUncheckAll: true, closeOnSelect: true}"
          [texts]="{defaultTitle: 'Source', uncheckAll: 'Reset'}"
          [options]="trans_src" [(ngModel)]="selected_SOURCE" (ngModelChange)="onSelect()"></ss-multiselect-dropdown>
`

**Comment by mrpatel15** [comment]
please help to fix this issues quickly.

**Comment by yakshit15** [comment]
@mrpatel15 any fix found for this?

**Comment by sagarloona4180** [comment]
please  use outside click directivre

**Comment by yakshit15** [comment]
@mrpatel15 @sagarloona4180 Please update node modules and this will work. Works fine now

**Comment by aditya777hp** [comment]
I have updated my node modules but still this is happening !!
I keep getting e.hasClass() is not a function error on my console.
