### ISSUE TITLE
Ability to perform form validation

### ISSUE THREAD

**Issue by siddharthaReddy** [softsimon/angular-2-dropdown-multiselect#43]
So, I have got this piece fitting and working exactly as expected in my project with code below.

I also want to perform a validation to check if atleast one option is selected from the dropdown. 

Using template driven form, I got the validation also working by adding 'required' attribute and reference variable (#market) binding to ngModel . 

```
//pixel.component.ts

  /* Multi Select Dropdown settings*/
  private multiSelectDropDownSettings: IMultiSelectSettings = {
    pullRight: true,
    enableSearch: false,
    showCheckAll: true,
    showUncheckAll: true,
    dynamicTitleMaxItems: 1
  };

  private multiSelectDropDownTexts: IMultiSelectTexts = {
    checkAll: 'Check all',
    uncheckAll: 'Clear',
    checked: 'checked',
    checkedPlural: 'checked',
    searchPlaceholder: 'Search..',
    defaultTitle: 'Select',
  };

  /* Options for dropdown */
  markets: Market[] = [
    {id: 1, name: "Denmark"},
    {id: 2, name: "France"},
    {id: 3, name: "Germany"},
    {id: 4, name: "Greece"}
  ];

//pixel.component.html
<form #pixelform="ngForm" novalidate (ngSubmit)="showParameters(pixelform, pixelform.valid)">
	<div class="form-group">
		<label for="name">Pixel Name</label>
		<input type="text" class="form-control" required id="name" name="name" #name="ngModel" [(ngModel)]="pixel.name">
		<small [hidden]="name.valid || (name.pristine && !pixelform.submitted)" class="text-danger">
			Name is required.
		</small>
	</div>
	<div class="form-group">
		<label for="market">Market</label>
		<ss-multiselect-dropdown  id="market" required name="market" [settings]="multiSelectDropDownSettings" [texts]="multiSelectDropDownTexts" [options]="markets" #market="ngModel" [(ngModel)]="pixel.market"></ss-multiselect-dropdown>
		<small [hidden]="market.valid || (market.pristine && !pixelform.submitted)" class="text-danger">
			Market must be selected.
		</small>
	</div>
	<button type="submit" class="btn btn-primary pull-right" [disabled]="!pixelform.form.valid">Submit</button>
</form>
```

But when I uncheck all the selections, angular doesn't update the 'ng-touched ng-dirty ng-valid' classes on `<ss-multiselect-dropdown>` and Submit button is not disabled. 

Can you please check what's missing in my code or if the approach is wrong ?

**Comment by insensitive** [comment]
Facing the same issue. Is there an update on this?

**Comment by nicholasguyett** [comment]
I'll look into this as soon as I can

**Comment by chaitanyanadavati** [comment]
<div *ngIf="selectedFeatures.errors && (selectedFeatures.dirty || selectedFeatures.touched)" class="alert alert-danger">
                            <div [hidden]="!selectedFeatures.errors.required">
                              Market must be selected.
                            </div>
                          </div>




Replace the <small></small> with the above code it will work.
