### ISSUE TITLE
Build Error during building project as npm package

### ISSUE THREAD

**Issue by Mrpankaj666** [softsimon/angular-2-dropdown-multiselect#434]
Hi Team,
 i am using angular 5 and angualr2-multiselect-dropdown 2.9.0 version , getting this error while building project as npm package, can someone assist what the exact issue because if i am using ng build then is no issue working fine..

BUILD ERROR
node_modules\angular2-multiselect-dropdown\multiselect.component.d.ts.AngularMultiSelect.html(7,95): : Type 'String' cannot be used as an index type.
node_modules\angular2-multiselect-dropdown\multiselect.component.d.ts.AngularMultiSelect.html(13,69): : Type 'String' cannot be used as an index type.
node_modules\angular2-multiselect-dropdown\multiselect.component.d.ts.AngularMultiSelect.html(12,123): : The left-hand side of an arithmetic operation must be of type
'any', 'number' or an enum type.
node_modules\angular2-multiselect-dropdown\multiselect.component.d.ts.AngularMultiSelect.html(31,106): : The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

**Comment by pablopandolfi** [comment]
Hi, I have the same problem

**Comment by MorlaRamakrishna** [comment]
We too!

**Comment by akshay-shekokar** [comment]
Does anyone found solution for this?

**Comment by ruchit072** [comment]
@akshay-shekokar @MorlaRamakrishna @pablopandolfi @Mrpankaj666 
To get it work, perform below actions.

1. Change datatype of all the properties to **any** in "multiselect.interface.d.ts" or interface DropdownSettings.
2. add property "item:any" in class AngularMultiSelect in multiselect.component.d.ts

After taking this two actions, I'm able to make production build. Changes also worked well.

**Comment by anupbangale** [comment]
> 2\. item:any

it solved my problem for the instance but i don't feel this is the good solution

**Comment by wsh92** [comment]
we are also facing the same issue. 
@anupbangale I agree with you, this is not a proper solution.

**Comment by wsh92** [comment]
After upgrading the version to 4.6.3, the issue is resolved.

**Comment by Mrpankaj666** [comment]
Closing the issue
