### ISSUE TITLE
Display error after upgrade to angular 6 

### ISSUE THREAD

**Issue by codedao-io** [softsimon/angular-2-dropdown-multiselect#444]
After i upgraded to angular 6 , dropdown display like image , how to fix this error ?
I use "bootstrap": "^4.1.3"

![angular-2-dropdown-multiselect-error-display](https://user-images.githubusercontent.com/42933475/45070099-e3344900-b0f9-11e8-876d-d772af3d2998.png)

**Comment by maxsands1503** [comment]
There is a closed issue that solves this already. https://github.com/softsimon/angular-2-dropdown-multiselect/issues/431
