### ISSUE TITLE
Support for optgroups, yay or nay?

### ISSUE THREAD

**Issue by ghost** [softsimon/angular-2-dropdown-multiselect#48]
Does this have support for `optgroups`?

**Comment by nicholasguyett** [comment]
There is currently no support for opt-groups.  However, I think its reasonable to add support when I find time to implement it.

**Comment by bkinsey808** [comment]
Yes please! optgroups would bring this up to feature parity with angularjs isteven multiselect which has "categories", essentially the same thing. I currently have an large ng1 app I want to migrate to ng2, and this is one of the key features holding me back at the moment.

https://github.com/isteven/angular-multi-select

**Comment by chris--jones** [comment]
I've implemented this for another project, just cleaning it up and I'll send through a PR.

**Comment by bkinsey808** [comment]
@chris--jones that looks great! Can I trouble you for one additional feature? isteven multiselect supports clicking on the category (optgroup) itself to select or unselect all of the items in that category.

**Comment by chris--jones** [comment]
I considered that, but as mentioned in the PR comment there probably needs to be some discussion around how that feature would work alongside the selectionLimit and autoUnselect options; unless it is simply disabled if either of these are enabled.

**Comment by bkinsey808** [comment]
Disabling if either of those are selected works for me.

**Comment by softsimon** [comment]
Pull request for this feature has been merged.

**Comment by troddick** [comment]
Is the option to click on the category (optgroup) a feature? From reading the above comments, if the 'selectionLimit' and 'autoUnselect' are disabled, then the optgroup can have a checkbox to select all options within the group? 
I add: 
`public multiSettings: IMultiSelectSettings;`
`ngOnInit(){
        this.multiSettings = {selectionLimit: 0, autoUnselect: false};`
and still am not getting a checkbox for the optgroup.

**Comment by chris--jones** [comment]
@bkinsey808 @troddick 
I've done some work on this, demo here:
https://chris--jones.github.io/angular-2-dropdown-multiselect/

It still needs further testing and review, but feel free to use it if you are so inclined:
https://github.com/chris--jones/angular-2-dropdown-multiselect/tree/develop

**Comment by troddick** [comment]
Great! Thanks!

**Comment by troddick** [comment]
Got it working with minor tweak to the updateParents() at line 357.
`updateParents() {`
`    this.parents = [];`
`    if (typeof(this.options) !== 'undefined'){ //check to see if there are options at this point (not there yet from ngOnInit call)`
`      this.options.forEach(option => {`
`        if(typeof(option.parentId) !== 'undefined'&&this.parents.indexOf(option.parentId)<0) {`
`          this.parents.push(option.parentId);`
`        }`
`      });`
`    }`
`  }`

**Comment by chris--jones** [comment]
@troddick 

The issue with options (or other properties) being undefined has been raised a few times under different circumstances; the control is not intended to be used with an uninitialised inputs; this means that although your code might work with that change you may encounter issues elsewhere if you don't initialise your options.

A better approach might be to make sure your options are initialised to an empty array even if you intend to populate the options immediately after.
e.g.
```typescript
private options: IMultiSelectOption[] = [];
```

**Comment by troddick** [comment]
Interesting. I populate the options in my ngOnInit() and assumed that was enough. 
I changed it to initializing my options right away and removed the undefined check from the lib code and you are correct, all runs smoothly.
Thanks.

**Comment by grimace** [comment]
sorry, but I wasn't quite sure from this thread if optgroups are now supported.  Are they? If so, how do I use them?
