### ISSUE TITLE
Support for Material design

### ISSUE THREAD

**Issue by naveenballa** [softsimon/angular-2-dropdown-multiselect#49]
hi @softsimon 
Is there any material design support for this component.

**Comment by naveedahmed1** [comment]
I was about to suggest this and it shouldn't be very difficult to implement.

In component, we can add
`import { MaterialModule } from '@angular/material';
`
In template:
```
<li *ngFor="let option of options | searchFilter:searchFilterText">
            <md-checkbox [checked]="isSelected(option)"  (change)="setSelected($event, option)">{{ option.name }}</md-checkbox>
        </li>
```

Some options in settings could be provided for material to activate this part of the template instead of normal checkboxes.

**Comment by naveenballa** [comment]
@softsimon Any update on this?

**Comment by softsimon** [comment]
@naveenballa No updates yet. Haven't tried material design.

**Comment by ermarkar** [comment]
Unable to implement in my project :(

https://stackoverflow.com/questions/42692044/how-to-use-angular-2-dropdown-multiselect

**Comment by softsimon** [comment]
/index.js doesn't exist.
try

```
'angular-2-dropdown-multiselect': {
        main: 'src/multiselect-dropdown.js',
        defaultExtension: 'js'
  }
```

Or use angular-cli (webpack) ;-)

**Comment by ermarkar** [comment]
this is working now. bootstrap4 is required , right ?

**Comment by softsimon** [comment]
Nope. Bootstrap 3 or 4.

**Comment by ermarkar** [comment]
How can I set the width? I have tried style property with width :100%. but this is not working :(

**Comment by chris--jones** [comment]
@ermarkar you need to set the style on the button, not the parent control, try adding a custom class to ```buttonClasses```

to see this in action try my demo page, and add form-control to the buttonClasses list. 
https://chris--jones.github.io/angular-2-dropdown-multiselect/

Note that I'm not recommending use of the form-control class it's just that it's built into bootstrap so already available, it's semantically wrong and will add an inset shadow - create your own class instead.

**Comment by chris--jones** [comment]
@naveedahmed1 One of the nice things about this control is that it has a "soft" dependency on bootstrap (you can technically run it without bootstrap css and just supply your own css if you need to).

You can already achieve a material-like design by omitting the bootstrap css and using custom css and javascript:
![image](https://cloud.githubusercontent.com/assets/10459377/25034766/3974e446-212c-11e7-8c88-b6301e2eb314.png)

I think to allow use of other components for the container, trigger button, checkboxes and list-items would require extending the component to allow custom rendering functions for these components and probably some memoization to prevent expensive re-rendering.

**Comment by chris--jones** [comment]
Unofficially you can customise a lot with the CSS (see above), but as this is primarily a bootstrap component, I'm closing this as unsupported.

@softsimon I'd be interested in working with you on a more generic dropdown select (I think I recall you suggesting something like ngx-dropdown-multiselect) with more styling flexibility.
