### ISSUE TITLE
dropdown seems to close on select even when setting is false

### ISSUE THREAD

**Issue by TheManSpeaker** [softsimon/angular-2-dropdown-multiselect#5]
the title is pretty much self-explanatory - I would look into this but I unfortunately don't have the time at the moment and this isn't a big deal for me.

**Comment by softsimon** [comment]
I have tried and it works. Try with the latest version updated to rc6.

**Comment by nicholasguyett** [comment]
@TheManSpeaker, if your issue persists even after upgrading to the latest version, can you provide an example in plunkr which demonstrates the problem so we can reproduce?

**Comment by lmq009** [comment]
I had the same problem.  

My previous code:
 get options() {
          return list.map(item => {id: item.dbId, name:item.dbName});
}

It seems causing all the <li> of options isolated. ( target.parentElement  is null )

It works fine now after I changed my code to:
this.options = list.map(item => ({id: item.dbId, name:item.dbName}));

So, If we can make sure the options is ready when rendering this Multiselect component, this issue could be  avoided.

**Comment by viliks** [comment]
It's a bug in dropdown. stopImmediatePropagation must be called in setSelected.

```
setSelected(event: Event, option: IMultiSelectOption) {
    event.stopImmediatePropagation();
......
```

**Comment by chris--jones** [comment]
Can you provide more to try and reproduce this? The event propagation should not trigger close unless it's outside the component container.

**Comment by viliks** [comment]
It is exactly as @lmq009 writes. If getter is used for options, list is closed after click. If the getter function is replaced with component property, everything is working fine.
