### ISSUE TITLE
Showing Error on console : Can't bind to 'ngModel' since it isn't a known property of 'ss-multiselect-dropdown'.

### ISSUE THREAD

**Issue by ronakjain-2** [softsimon/angular-2-dropdown-multiselect#53]
![screenshot from 2017-01-05 18 29 17](https://cloud.githubusercontent.com/assets/24937067/21681351/f415ed3c-d374-11e6-8f0b-911e603ebb94.png)
Hi,

I am using this package in my project. But i am finding an error 'Can't bind to 'ngModel' since it isn't a known property of 'ss-multiselect-dropdown'. 

Process which i have done is:
1.app.module->

import {MultiselectDropdownModule} from 'angular-2-dropdown-multiselect/src/multiselect-dropdown';
@NgModule({
               imports:      [ BrowserModule, AppRoutingModule, ChartModule,                 DatepickerModule,MultiSelectModule,MultiselectDropdownModule ],
...//
})

2. Systemjs.config

(function (global) {
  System.config({
  	paths: {
      // paths serve as alias
      'npm:': 'node_modules/'
    },
    // map tells the System loader where to look for things
    map: {
      'angular-2-dropdown-multiselect/src/multiselect-dropdown':'npm:angular-2-dropdown-multiselect/src/multiselect-dropdown'
    },
    packages: {
      // add packages here
      'angular-2-dropdown-multiselect/src/multiselect-dropdown':{
        main:'../multiselect-dropdown',
        defaultExtension:'js'
      }
    }
  });
})(this);

3. header.component

import { Component,Input } from '@angular/core';
import {IMultiSelectOption} from 'angular-2-dropdown-multiselect/src/multiselect-dropdown';

@Component({
  moduleId: module.id,
  selector: 'header',
  templateUrl: 'header.component.html'
})
export class HeaderComponent{
	
  private selectedOptions: number[];
  private myOptions: IMultiSelectOption[] = [
        { id: 1, name: 'Option 1' },
        { id: 2, name: 'Option 2' },
  ];
	constructor(private contextService: ContextService){
	};
}

4. header(html):

<li>
     <ss-multiselect-dropdown [options]="myOptions" [(ngModel)]="selectedOptions"     (ngModelChange)="onChange($event)"></ss-multiselect-dropdown>
</li>

Version Details:

ubuntu 14.04

angular-2-dropdown-multiselect@0.3.3 extraneous

node.js v7.3.0

npm 3.10.10

Can you please provide any demo example of this package implementation ?

**Comment by nicholasguyett** [comment]
Quick question, why do you have both `[(ngModel)]` and (ngModelChange)`?  As the `[(ngModel)]="model"` syntax is equivalent to `[ngModel]="model"` and `(ngModelChange)=""model = $event`, I'm not sure it will let you bind `ngModelChange` twice.

Secondly, have you included the forms module in your AppModule imports?

**Comment by thehashrocket** [comment]
@nicholasguyett it's happening for me as well? See [this thread](https://github.com/softsimon/angular-2-dropdown-multiselect/issues/31)

**Comment by nicholasguyett** [comment]
@thehashrocket, the bug in #31 seems like its the result of a different issue (which I'll try to work on when I get time, I've been busier than I'd like lately).

**Comment by PierreDuc** [comment]
The usage in your readme.md shows to use  `[(ngModel)]` with `(ngModelChange)`. So you can understand their confusion :)

`<ss-multiselect-dropdown` [options]="myOptions" [(ngModel)]="selectedOptions" (ngModelChange)="onChange($event)"></ss-multiselect-dropdown>`

**Comment by CruelEngine** [comment]
@ronakjain-2 i faced the same issue . But importing the FormsModule in app.module.ts solved the issue.

**Comment by softsimon** [comment]
Make sure to include FormsModule.
