### ISSUE TITLE
Outdated NPM package

### ISSUE THREAD

**Issue by davidich** [softsimon/angular-2-dropdown-multiselect#54]
Even though repository contains up-to-date package.json file, in npm repository the file is outdated. There package requires RXJS@5.0.0-rc.4 and cause npm to complain:
"UNMET PEER DEPENDENCY rxjs@5.0.2" 

Please, update the package in order to bump up version of RXJS dependency.
https://unpkg.com/angular-2-dropdown-multiselect/package.json

**Comment by softsimon** [comment]
Fixed in new release.
