### ISSUE TITLE
Failed to load multiselect-dropdown.html

### ISSUE THREAD

**Issue by davidich** [softsimon/angular-2-dropdown-multiselect#56]
I'm using SystemJS as module loader and configured it as following:
       
```
(function (global) {
  System.config({
    paths: {
      'npm:': "node_modules/"
    },
    map: {
      // ...
      'angular-2-dropdown-multiselect': "npm:angular-2-dropdown-multiselect/src/multiselect-dropdown.js",
    ...
```

After 0.3.4 release, an html template was extracted into a separate file and that broke my setup. Now I'm getting a nasty error:
```
Unhandled Promise rejection: Failed to load multiselect-dropdown.html ;
Zone: <root> ; 
Task: Promise.then ; 
Value: Failed to load multiselect-dropdown.html
```

I tried to fix it with another line in map section of SystemJS config: 
```
'multiselect-dropdown.html': "npm:angular-2-dropdown-multiselect/src/multiselect-dropdown.html"
```
but it didn't help.

Could you, please, suggest a solution or guide me to a more appropriate way of including your library?

**Comment by asrafshaikh86** [comment]
Unhandled Promise rejection: Failed to load multiselect-dropdown.html ; Zone: <root> ; Task: Promise.then ; Value: Failed to load multiselect-dropdown.html undefined
Error: Uncaught (in promise): Failed to load multiselect-dropdown.html
error occur

**Comment by nicholasguyett** [comment]
Just updated and I'm getting the same issue...

**Comment by nicholasguyett** [comment]
Caused by commit https://github.com/softsimon/angular-2-dropdown-multiselect/commit/44532ebcf2210b49ee1f5771eef83022ca332e4b.  You won't be able to map the file location as its loaded by angular, not SystemJS.

**Temporary workaround is to downgrade to 0.3.3** (which I'll be doing until I can spend more time on this).  The only significant changes I see from this workaround are some slight style changes that might make it easier to resize the dropdown and the removal of a "peer dependency" error which is safely ignorable.  If neither of those are dealbreakers, that's my recommendation.

I'll leave this issue open until I find a way to make this work with SystemJS.

**Comment by asrafshaikh86** [comment]
It is working for me.
Just change  templateUrl: './multiselect-dropdown.html' 
 to  
 templateUrl: 'node_modules/angular-2-dropdown-multiselect/src/multiselect-dropdown.html'  
in multiselect-dropdown.ts file.

**Comment by nicholasguyett** [comment]
@davidich @asrafshaikh86 Are you doing the single-file export with SystemJs or are you using the regular dynamic load (requests each module as its being imported)?

**Comment by nicholasguyett** [comment]
@davidich @asrafshaikh86 Are you doing the single-file export with SystemJs or are you using the regular dynamic load (requests each module as its being imported)?

**Comment by davidich** [comment]
@nicholasguyett , I'm using regular dynamic load.

**Comment by navcoder** [comment]
I am also facing similar issue on creating Production build. The thing is that the latest download doesn't get any multiselect-dropdown.js. It only has .ts and .html file.
On using Gulp and SystemJS setup(https://github.com/mgechev/angular-seed), this doesn't build the node_modules so I have to manually copy the old multiselect-dropdown.js. Now this .ts file has templateUrl:'.multiselect-dropdown.html', which obviously isn't there and hence the build fails.
This seems to work with WebPack version.
For time now, I have created JS file with template embeded in the JS file and this works. 
Is there any proper solution to make it work with Gulp and SystemJs application?

**Comment by nicholasguyett** [comment]
I think the way forward for now is to go back to inlining the template.  A separate file is best practice, but its looking to be too complicated to make it compatible with the different build systems.  Once relative template urls are a bit more stable we can split it out again, but for now function trumps form.

I've pushed a commit inlining the template again.  Once its pushed to npm, it *should* fix this.  It fixed it in my build, at least.

**Comment by nicholasguyett** [comment]
Fix should be in the latest release.  Please try the latest and confirm that it resolves the issue for you.

**Comment by AjaySinghKatara** [comment]
Hi, I am trying to run this npm in Angular-4 and getting "Error: Fetch error: 404 Not Found".

Please let me know, will this be compatible to with Angular-4 or not? If not then, could you please suggest me any other "Multi-select dropdown" npm which should be compatible with Angular-4

**Comment by softsimon** [comment]
@AjaySinghKatara this component is only compatible with Angular 4.x as of now.
