### ISSUE TITLE
Throwing error in AoT production build

### ISSUE THREAD

**Issue by shreekantha** [softsimon/angular-2-dropdown-multiselect#58]
I am using Angular CLI, when I try to build app with  command "ng build --prod --aot", it started throwing error.

 ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', 
function calls are not supported. Consider replacing the function or lambda with a reference to a
n exported function, resolving symbol Injectable in /home/spaneos/Videos/ng2aot/**node_modules/angu
lar-2-dropdown-multiselect/node_modules/@angular/core/src/di/metadata.d.ts, resolving symbol Opaq
ueToken** in /home/spaneos/Videos/**ng2aot/node_modules/angular-2-dropdown-multiselect/node_modules/@
angular/core/src/di/opaque_token.d.ts, resolving symbol OpaqueToken** in /home/spaneos/Videos/**ng2ao
t/node_modules/angular-2-dropdown-multiselect/node_modules/@angular/core/src/di/opaque_token.d.ts**
                                                                                                 
ERROR in ./src/main.ts                                                                           
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/home/spaneos/V
ideos/ng2aot/src'                                                                                
 @ ./src/main.ts 4:0-74                                                                          
 @ multi main                                                                                    

Please help me on this. We are going to production in next week.

**Comment by softsimon** [comment]
Are you sure it's related to this component? I ran "ng build --prod --aot" just a while ago with the latest version and no issues.

**Comment by shreekantha** [comment]
Yes it is related to multi select drop down only and I am not using any other third party libraries except multi select drop down.

**Comment by nicholasguyett** [comment]
@shreekantha, why are you certain it is because of this library?

Have you tried running the build process with and without the package included?

**Comment by shreekantha** [comment]
Yes I tried , without this package, project is built successfully.

**Comment by shreekantha** [comment]
@softsimon , please help me to resolve  this issue.

**Comment by shreekantha** [comment]
@softsimon, Issue has been resolved.
I forked your project and moved all dependencies into devDependencies in package.json.
I did npm pack and installed package into project, then I built using "ng build --prod --aot".
Project built successfully .

**Comment by shreekantha** [comment]
@softsimon , It will be great help for me if  you can  re-publish your project to npm, so that we can use in our project to build in AoT.


Awaiting your response

Thank you so much for this fantastic  multi select library.

**Comment by softsimon** [comment]
@shreekantha I can do it tonight. Can you make a pull request in the meantime?
