### ISSUE TITLE
Bootstrap CSS3 included in the index.html is changing the CSS of other components

### ISSUE THREAD

**Issue by CruelEngine** [softsimon/angular-2-dropdown-multiselect#61]
I attached bootstrap.css in index.html  but now all the css of other components are being changed .

Any workaround?

**Comment by nicholasguyett** [comment]
Are you using this in combination with another css framework?  If so, there might be a conflict between bootstrap and your other framework.  Unfortunately, resolving that is an issue outside the scope of this project.
