### ISSUE TITLE
problem with refreshing dynamicTitle onInit in parent component

### ISSUE THREAD

**Issue by witgithub** [softsimon/angular-2-dropdown-multiselect#62]
is there any solution for updating dynamicTitle in parent component same like updateNumSelected ? i'm getting titles only after checking checkbox and i cannot find way to update it before action, im getting only sum of checked checkboxes.

**Comment by chris--jones** [comment]
Are you trying to update the title dynamically yourself?

There's now a fixedTitle option if you want to leave the title as the default and not have it reflect the number of checked items.

**Comment by chris--jones** [comment]
Closed due to inactivity, hope your issue was resolved 😄
