### ISSUE TITLE
Single select toggle

### ISSUE THREAD

**Issue by Marcdup1** [softsimon/angular-2-dropdown-multiselect#63]
Hi,

It would be nice when its single select and you can toggle between each item without having to click on it first to uncheck it.

**Comment by Marcdup1** [comment]
I know its just a nice to have, you can get the desired effect like this:
```
onChange(items) {
        if (items.length >= 2) {
            this.selectedOptions.shift();
        }
    }
```

**Comment by chris--jones** [comment]
This option was added with #27 

Set autoUnselect true and selectionLimit to 1 (the documentation needs updating)

**Comment by Marcdup1** [comment]
@chris--jones Thank you for that!
