### ISSUE TITLE
System.register is not supported by webpack

### ISSUE THREAD

**Issue by pranavsreedhar92** [softsimon/angular-2-dropdown-multiselect#68]
After implementing multi-select getting error.

WARNING in ./~/angular-2-dropdown-multiselect/src/multiselect-dropdown.js
System.register is not supported by webpack.
 @ ./src/app/app.module.ts 44:29-95
 @ ./src/main.ts
 @ multi main
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 543 kB [entry] [rendered]
        [0] ./~/lodash/lodash.js 540 kB {0} [built]
        [1] (webpack)/buildin/global.js 506 bytes {0} [built]
        [2] (webpack)/buildin/module.js 548 bytes {0} [built]
        [3] ./~/html-webpack-plugin/lib/loader.js!./src/index.html 2.74 kB {0} [built]
Child extract-text-webpack-plugin:

**Comment by nicholasguyett** [comment]
Compiled js should now be a commonjs module, which is compatible with webpack.  Please try again with the latest to see if it resolves this issue.

**Comment by nicholasguyett** [comment]
No response in 7 days.  Assuming the fix worked and closing issue.
