### ISSUE TITLE
Old Code/Refactor

### ISSUE THREAD

**Issue by KyleJayMaxwell** [softsimon/angular-2-dropdown-multiselect#7]
I've have tried to update this code to the best of my ability, but have run into a slight problem as I don't know Angular 2 very well. I have been looking up the problem trying to diagnosis it and found that I'm not the only one with this problem: http://stackoverflow.com/questions/38811532/cant-bind-to-ngformcontrol-since-it-isnt-a-known-native-property Just wondering if your plan is to do maintenance on it. I guess it's the forms.

**Comment by softsimon** [comment]
I had planned to keep it updated and working. Just haven't had the time recently.... But soon.
