### ISSUE TITLE
selectedOptions return need Id & Name

### ISSUE THREAD

**Issue by 602991** [softsimon/angular-2-dropdown-multiselect#72]
Hi Team,

As of now selectedOptions returns only id, but we need id and name also. Please provide any solutions for this.

Thanks you !!

**Comment by chris--jones** [comment]
I believe the original intent was that you could use the id to obtain any details about your model
e.g.
```
var options = [
        { id: 1, name: 'Option 1', color: 'blue' },
        { id: 2, name: 'Option 2', color: 'red' },
        { id: 3, name: 'Option 3', color: 'yellow' },
        { id: 4, name: 'Option 4', color: 'green' },
        { id: 5, name: 'Option 5', color: 'purple' },
    ];

(selectedOptions = [1,3])

options.filter(option => selectedOptions.indexOf(option.id) >= 0)

[
  {"id":1,"name":"Option 1","color":"blue"},
  {"id":3,"name":"Option 3","color":"yellow"}
]

```

In recent updates the id now permits objects so you could also just make your ids contain the actual id and the name, but I wouldn't recommend this.

**Comment by nicholasguyett** [comment]
@chris--jones is correct.  If you want the value set in "name", you should get that data from your array directly.  The "id" property is what is being set as the value model, and can be an object, as stated.  If the actual value you want is the label, then you can set that for both the id and the label.
