### ISSUE TITLE
dropdownClosed not firing

### ISSUE THREAD

**Issue by sarge5766** [softsimon/angular-2-dropdown-multiselect#73]
Has anyone else noticed that dropdownClosed not firing when clicking away from dropdown?

It only seems to fire when closing via clicking on the multi-select list itself.

**Comment by gogo217** [comment]
drop down can't be closed when click outside of it.

**Comment by softsimon** [comment]
I haven't noticed. It works in my implementations.

**Comment by iacii** [comment]
It looks like it only fires if you click on the dropdown itself to close it, but not if you click outside it somewhere else on the page.

I do not see `this.dropdownClosed.emit()` in this method:

```js
@HostListener('document: click', ['$event.target'])
  onClick(target: HTMLElement) {
    let parentFound = false;
    while (target != null && !parentFound) {
      if (target === this.element.nativeElement) {
        parentFound = true;
      }
      target = target.parentElement;
    }
    if (!parentFound) {
      this.isVisible = false;
    }
  }
```

Maybe I'm reading this wrong, but I believe adding that line after `this.isVisible = false` would solve this.
