### ISSUE TITLE
selected items are resticted to array of number (id)

### ISSUE THREAD

**Issue by josika** [softsimon/angular-2-dropdown-multiselect#8]
now it is: model: number[];

it could be : model: Array<IMultiSelectOption>;

**Comment by josika** [comment]
It is a great work guys :) thanks for the component, i hope you will keep working on it :)

i had forked the project and made quick fix, you can check it if you would like

https://github.com/josika/angular-2-dropdown-multiselect

**Comment by softsimon** [comment]
Is object instead of id's the preferred way for most use cases or are there any use case where numbers would be prefered? You should make a pull request of your fork 👍

**Comment by nicholasguyett** [comment]
@softsimon, using an object isn't always the preferred instance, but strings on the other hand are quite common (see [this issue](https://github.com/softsimon/angular-2-dropdown-multiselect/issues/39#issue-195351153) as an example), so it certainly shouldn't be restricted entirely to numbers.

Given this is purely a typing issue, I'll make quick commit for it, as the minimal nature of the change isn't worth the overhead of waiting on a pull request.
