### ISSUE TITLE
Uncheck a selected value based on current user selection

### ISSUE THREAD

**Issue by bryan-mwas** [softsimon/angular-2-dropdown-multiselect#81]
How do I unselect a value say _Option one_ when a user selects a _Option Two_ in the list

**Comment by chris--jones** [comment]
Is this what you're looking for? (second from bottom, auto-unselect) : https://chris--jones.github.io/angular-2-dropdown-multiselect/

If so, just set autoUnselect to true in your options; sorry, I've yet to submit a pull request with the updated README.

**Comment by bryan-mwas** [comment]
Yes I am referring to the first option whereby 
_ to deselect option one if option two is selected, but leave it selected when option three is selected_

**Comment by nicholasguyett** [comment]
@bryan-mwas, you'll have to implement that in your component.  I'd recommend using a custom getter and setter which produces this effect for you.  If you do that, it will automatically update the component

**Comment by bryan-mwas** [comment]
Could you please show me how? To have a getter and setter that produces the
desired effect
