### ISSUE TITLE
Breaks on latest version: ng-template is not a known element

### ISSUE THREAD

**Issue by shripalsoni04** [softsimon/angular-2-dropdown-multiselect#84]
Hi,
Thanks for creating this nice dropdown plugin 👍 

I installed the latest version (v 1.0.0) of this plugin from npm and the application is breaking with below error:
```
Unhandled Promise rejection: Template parse errors:
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("!option.isLabel && setSelected($event, option)" [class.dropdown-header]="option.isLabel">
          [ERROR ->]<ng-template [ngIf]="option.isLabel">
            {{ option.name }}
          </ng-template>
...
...
```

I think it should be `<template>` instead of `<ng-template>` as `ng-template` is not a known component in angular 2.

It will be great if you can provide solution for this issue.

Thanks.

**Comment by softsimon** [comment]
Ah sorry about that. I was running Angular 3 RC. Will publish a fix in a few hours.

**Comment by shripalsoni04** [comment]
Great! Thanks for very quick reply 👍
