### ISSUE TITLE
showCheckAll ="true" doesn't make the check all option show up

### ISSUE THREAD

**Issue by Seeker93** [softsimon/angular-2-dropdown-multiselect#85]
HI

I'm debugging someone elses code, and he used this component.

When I change the custom settings array option to "showCheckAll:true" I still don't get the check all option.  

Settings:

```
>    dropdownSettings: IMultiSelectSettings = {
        pullRight: false,
        enableSearch: true,
        checkedStyle: 'checkboxes',
        buttonClasses: 'btn btn-default form-control',
        selectionLimit: 0,
        closeOnSelect: false,
        showCheckAll: true,
        showUncheckAll: true,
        dynamicTitleMaxItems: 2,
        maxHeight: '300px',
    };
```
HTML:

```
       <dropdown [options]="terminalsOptions"
                                        [enabled]="model.perMerchant"
                                        (selectedModel)="terminalOptionsUpdated($event)"
                                        [settings]="dropdownSettings" [texts]="dropdownTexts"></dropdown>
```

Please tell me if I am missing something / being an idiot.

**Comment by softsimon** [comment]
Cannot reproduce.

**Comment by chris--jones** [comment]
> When I change the custom settings array option to "showCheckAll:true" I still don't get the check all option.

Are you initialising the control with those settings, or trying to update the settings after initialisation?
If you're trying to dynamically change the settings by altering your original settings object the changes won't be detected due to shallow change detection (only comparing reference).

If you wish to force a settings reload you'll have to change the reference.
e.g.
```typescript
    // modify settings
    this.dropdownSettings.showCheckAll = true;
    // reload settings by creating a new object reference
    this.dropdownSettings = Object.assign({}, this.dropdownSettings);
```

**Comment by Seeker93** [comment]
HI everyone. Thanks for the replies.  I forgot to close this issue, and apologize. The issue was that the person who wrote the code manually removed the portion that dealing with the check all option for some reason. Using the original code worked fine. Sorry for the trouble.
