### ISSUE TITLE
cross icon on selected items

### ISSUE THREAD

**Issue by ermarkar** [softsimon/angular-2-dropdown-multiselect#89]
Is there any option to show cross icon on selected item to remove them directly?

And option to set the width property of "Select" button?

**Comment by softsimon** [comment]
Do you want to from the dropdown be able to remove options completely from the list of options?

**Comment by ermarkar** [comment]
If I select 3 item and that are visible as button name then there should cross icon on the right top corner of every selected item. Now if i click on cross of an individual item it should get un selected from selected list

**Comment by ermarkar** [comment]
and how can I set width of button ?

**Comment by softsimon** [comment]
:host /deep/ ss-multiselect-dropdown button.dropdown-toggle {
	width: 200px;
}

**Comment by softsimon** [comment]
I think I understand now. You want the main button to work as a tag token field like this? https://camo.githubusercontent.com/1b4f9be25a1684c0dc5e10922afe06b81ec9d8df/687474703a2f2f692e696d6775722e636f6d2f4454314f6b62422e706e67

**Comment by ermarkar** [comment]
yes!

**Comment by ermarkar** [comment]
can `dynamicTitleMaxItems` adjust according to the width of drop-down button ?

**Comment by softsimon** [comment]
The feature you request will not be implemented at this moment. It feels too much away from the basic usage. It cannot both be a dropdown component and a tag token field.
