### ISSUE TITLE
Error on Safari when dropdown appears

### ISSUE THREAD

**Issue by pgeyman** [softsimon/angular-2-dropdown-multiselect#90]
On Safari, when you click to view the dropdown, the following error appears:
Error: Error in ./MultiselectDropdown class MultiselectDropdown - inline template:30:30 caused by: Attempted to assign to readonly property.

The same code worked fine on Chrome.
I am using the latest version of angular-2-dropdown-multiselect (v1.0.2)
It worked on Safari when we were using v0.3.5.
Just reverted to v0.4.1 and it works

**Comment by softsimon** [comment]
I found the error and got a working fix. Angular-bug https://github.com/angular/angular/issues/14910
