### ISSUE TITLE
No way to disable control?

### ISSUE THREAD

**Issue by screamingtiger** [softsimon/angular-2-dropdown-multiselect#91]
I need to be able to disable the control dynamically, how can this be done?
The OnClick handler does not have a catch to check for disabled so the values can be changed.

**Comment by TeodorKolev** [comment]
Can you please give example how to set disable - already checked options from here. Is that possible?
`<ss-multiselect-dropdown [options]="myOptions" [texts]="myTexts" [settings]="mySettings" [(ngModel)]="optionsModel"></ss-multiselect-dropdown>`

**Comment by fabrizziocht** [comment]
<ss-multiselect-dropdown [disabled]="VARIABLE" ....

**Comment by xjapatel** [comment]
He, do we have a disabled option available.
