### ISSUE TITLE
Display all the available options with checkbox selection

### ISSUE THREAD

**Issue by prabhurangan** [softsimon/angular-2-dropdown-multiselect#92]
Team,

Do we have an option/settings to display all the available options with checkbox selection like <select multiple></select>

**Comment by nicholasguyett** [comment]
Did you intend to include an example with this?

The component always shows all available options when opened, so I don't quite understand your question.

**Comment by prabhurangan** [comment]
<img width="171" alt="screen shot 2017-03-13 at 9 20 32 pm" src="https://cloud.githubusercontent.com/assets/16012151/23885792/edf9e294-0832-11e7-83d5-6e5bc36c0172.png">

instead of the top portion i would like to have the bottom portion always expanded and show the options with checkbox??

**Comment by prabhurangan** [comment]
similar to <select multiple /> in html; like below:
<img width="169" alt="screen shot 2017-03-13 at 9 24 14 pm" src="https://cloud.githubusercontent.com/assets/16012151/23885857/776959f6-0833-11e7-8da3-a703f865447c.png">

**Comment by nicholasguyett** [comment]
Okay.  So you basically want an option to have it be always expanded?

I'm not entirely sure this component is the right choice for that.   You might be better off writing your own component, since all you want is the checkbox list and a select count.

I'm going to close this, for now.  But if you have a specific, compelling reason why you want to use this component without the drop down component of it, then I can re-open the task.

**Comment by prabhurangan** [comment]
First of all i would like to thank you all for the great work.  it has lots
of features in it.

My ask here is, I would like to see the list of options user selected from
the dropdown, instead of saying '4 Checked'.

FYI: Attached screenshot

**Comment by softsimon** [comment]
@prabhurangan Just set the dynamicTitleMaxItems setting to a high value.

**Comment by prabhurangan** [comment]
Hi Simon,

It works perfect! Thank you.

I am getting this warning:  'WARNING: sanitizing unsafe style value cursor:
pointer (see http://g.co/ng/security#xss).'  on click of the dropdown
button???

**Comment by softsimon** [comment]
@prabhurangan I know, it's been fixed in master. I will publish a new version tonight or tomorrow.

**Comment by prabhurangan** [comment]
Hi Simon,

Thank you.

'CheckAll' option not working the first time (created a ticket for the same)

EXCEPTION: Error in ./MultiselectDropdown class MultiselectDropdown -
inline template:18:8 caused by: Cannot read property 'indexOf' of null
ErrorHandler.handleError @ error_handler.js:54
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:234
SafeSubscriber.next @ Subscriber.js:183
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
ZoneDelegate.handleError @ zone.js:334
Zone.runTask @ zone.js:169
ZoneTask.invoke @ zone.js:416
error_handler.js:56 ORIGINAL EXCEPTION: Cannot read property 'indexOf' of
null
ErrorHandler.handleError @ error_handler.js:56
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:234
SafeSubscriber.next @ Subscriber.js:183
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
ZoneDelegate.handleError @ zone.js:334
Zone.runTask @ zone.js:169
ZoneTask.invoke @ zone.js:416
error_handler.js:59 ORIGINAL STACKTRACE:
ErrorHandler.handleError @ error_handler.js:59
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:234
SafeSubscriber.next @ Subscriber.js:183
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
ZoneDelegate.handleError @ zone.js:334
Zone.runTask @ zone.js:169
ZoneTask.invoke @ zone.js:416
error_handler.js:60 TypeError: Cannot read property 'indexOf' of null
at http://localhost:4200/vendor.bundle.js:126314:28
at Array.map (native)
at MultiselectDropdown.checkAll (
http://localhost:4200/vendor.bundle.js:126313:14)
at View_MultiselectDropdown5.handleEvent_2
(/MultiselectDropdownModule/MultiselectDropdown/component.ngfactory.js:258:56)
at View_MultiselectDropdown5. (
http://localhost:4200/vendor.bundle.js:102311:37)
at HTMLAnchorElement. (http://localhost:4200/vendor.bundle.js:51586:53)
at ZoneDelegate.invokeTask (
http://localhost:4200/polyfills.bundle.js:6590:31)
at Object.onInvokeTask (http://localhost:4200/vendor.bundle.js:35808:37)
at ZoneDelegate.invokeTask (
http://localhost:4200/polyfills.bundle.js:6589:36)
at Zone.runTask (http://localhost:4200/polyfills.bundle.js:6393:47)
at HTMLAnchorElement.ZoneTask.invoke (
http://localhost:4200/polyfills.bundle.js:6643:38)
ErrorHandler.handleError @ error_handler.js:60
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:234
SafeSubscriber.next @ Subscriber.js:183
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
ZoneDelegate.handleError @ zone.js:334
Zone.runTask @ zone.js:169
ZoneTask.invoke @ zone.js:416
error_handler.js:63 ERROR CONTEXT:
ErrorHandler.handleError @ error_handler.js:63
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:234
SafeSubscriber.next @ Subscriber.js:183
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
ZoneDelegate.handleError @ zone.js:334
Zone.runTask @ zone.js:169
ZoneTask.invoke @ zone.js:416
error_handler.js:64 DebugContext {_view: View_MultiselectDropdown5,
_nodeIndex: 2, _tplRow: 18, _tplCol: 8}
ErrorHandler.handleError @ error_handler.js:64
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:234
SafeSubscriber.next @ Subscriber.js:183
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
ZoneDelegate.handleError @ zone.js:334
Zone.runTask @ zone.js:169
ZoneTask.invoke @ zone.js:416
Subscriber.js:238 Uncaught ViewWrappedError {__zone_symbol__error: Error:
Error in ./MultiselectDropdown class MultiselectDropdown - inline
template:18:8 caused by: Ca…, _nativeError: ZoneAwareError, originalError:
TypeError: Cannot read property 'indexOf' of null
at http://localhost:4200/vendor.bundle.js:1263…, context: DebugContext,
__zone_symbol__stack: "Error: Error in ./MultiselectDropdown class
Multis…ttp://localhost:4200/polyfills.bundle.js:6643:38)"…}
SafeSubscriber.__tryOrUnsub @ Subscriber.js:238
SafeSubscriber.next @ Subscriber.js:183
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
ZoneDelegate.handleError @ zone.js:334
Zone.runTask @ zone.js:169
ZoneTask.invoke @ zone.js:416

**Comment by nicholasguyett** [comment]
Sorry for misunderstanding your request, but I'm glad you got the answer you were looking for!
