### ISSUE TITLE
Array repeat issue without object

### ISSUE THREAD

**Issue by dineshk16feb** [softsimon/angular-2-dropdown-multiselect#93]
I am not able to repeat array values like

`myOptions = ["option 1", "option 2", "option 3"]`

is there any option for this.

**Comment by prabhurangan** [comment]
Edit your array like: [ {id: 'option 1', name: 'option 1'}, {id: 'option
2', name: 'option 2'}]

**Comment by softsimon** [comment]
I don't understand. Your options should be an array of objects with "name" and "id" property, and the model of selected items is an array of id

**Comment by dineshk16feb** [comment]
@softsimon My option is not array of object with "name" and "id", my array is like this,

`myOptions = ["option 1", "option 2", "option 3"]`

and I cant change because I need to change many places.

**Comment by softsimon** [comment]
This component is built around array of objects, so it's not possible to solve your case in a simple manner. You would need to rewrite most of the component. An array of primitive strings will not be supported, sorry.

**Comment by nicholasguyett** [comment]
If you a source array you want to use, just map your array using

```
arr.map(val => ({id: val, name: val}));
```

This allows you to keep your original list and still present the format this component expects.
