### ISSUE TITLE
Cursor: pointer  and  Argument of type 'boolean' is not assignable to parameter of type 'string'.

### ISSUE THREAD

**Issue by maabreve** [softsimon/angular-2-dropdown-multiselect#95]
Hi,

Im getting two erros when i try build using npm run build:aot or npm run build

ERROR in [at-loader] compiled\node_modules\angular-2-dropdown-multiselect\src\multiselect-dropdown.ngfactory.ts:795:11
    TS2322: Type '"" | "cursor: pointer"' is not assignable to type 'boolean'.
  Type '""' is not assignable to type 'boolean'.

AND

ERROR in [at-loader] compiled\node_modules\angular-2-dropdown-multiselect\src\multiselect-dropdown.ngfactory.ts:797:124
    TS2345: Argument of type 'boolean' is not assignable to parameter of type 'string'.

Thank you!

**Comment by softsimon** [comment]
Strange. I don't get this error with --aot --prod build angular-cli. It seems to be related to the value passed to bypassSecurityTrustStyle() which is and should be a string, but in your case it's complaining about not being a boolean?

I couldn't come up with an alternative way of conditionally adding style attributes without going through sanitizer.bypassSecurityTrustStyle...

**Comment by softsimon** [comment]
This should be fixed in the latest release. :) I found an alternative to this code.

**Comment by maabreve** [comment]
Many thanks for the prompt reply!
