### ISSUE TITLE
Can't bind to 'options' since it isn't a known property of 'ss-multiselect-dropdown'.

### ISSUE THREAD

**Issue by surensubhu** [softsimon/angular-2-dropdown-multiselect#96]
I installed the package successfully and followed the instruction in readme.md. But I am getting following error in the console if i run the application.

Can't bind to 'options' since it isn't a known property of 'ss-multiselect-dropdown'.
1. If 'ss-multiselect-dropdown' is an Angular component and it has 'options' input, then verify that it is part of this module.
2. If 'ss-multiselect-dropdown' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
              Roles
            </label>
            <ss-multiselect-dropdown [ERROR ->][options]="roleOptions" formControlName="roles"></ss-multiselect-dropdown>
          </div>
        <"): ContactComponent@96:37
'ss-multiselect-dropdown' is not a known element:
1. If 'ss-multiselect-dropdown' is an Angular component, then verify that it is part of this module.
2. If 'ss-multiselect-dropdown' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("
              Roles
            </label>
            [ERROR ->]<ss-multiselect-dropdown [options]="roleOptions" formControlName="roles"></ss-multiselect-dropdown>

**Comment by softsimon** [comment]
> 'ss-multiselect-dropdown' is not a known element:

Could it be that the MultiselectDropdownModule module isn't imported into your feature ngModule config?

**Comment by surensubhu** [comment]
no..I have imported that in my ngModule

 ],
  imports: [
    BrowserModule,
    CommonModule,
    HttpModule,
    FormsModule,
    ReactiveFormsModule,
    routing,
    BootstrapModalModule,
    FormModule,
    ReviewModule,
    MultiselectDropdownModule,

**Comment by softsimon** [comment]
If you are using the component in a child feature module you need to import it into that feature ngModule. Are you using feature modules or is this the only ngmodule config?

**Comment by surensubhu** [comment]
I added only on ngmodule config.. After adding to feature modules, it worked. Thanks!!

**Comment by softsimon** [comment]
I was confused about this as well. The "root module" imports are not global and need to be imported into all feature modules where they are used. You could aswell remove the import of DropdownModule in the root module.

**Comment by surensubhu** [comment]
oh..got it. it will be great if you mention this in your readme file. It might help others and save time.

**Comment by Hainesy** [comment]
If you have lots of modules you want to use in more than one feature module, the recommended practice is to import and export it from a shared module, then just import your shared module in all your feature modules.
