### ISSUE TITLE
Angular 4 <template> warning

### ISSUE THREAD

**Issue by infinitysky** [softsimon/angular-2-dropdown-multiselect#98]
Hi all,
I just upgraded my project from Angular 2 to Angular 4. After I start my project, I received a warning message about the <template>.

```
Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("!option.isLabel && setSelected($event, option)" [class.dropdown-header]="option.isLabel">
          [ERROR ->]<template [ngIf]="option.isLabel">
            {{ option.name }}
          </template>
"): MultiselectDropdown@36:10

```

I checked the source code. Just edit the line No. `126` and change the < 

```
<template [ngIf]="option.isLabel">
            {{ option.name }}
 </template>>
```
to 

```
 <ng-templat [ngIf]="option.isLabel">
            {{ option.name }}
  </ng-templat >
```

Then, the warning will disappear.

**Comment by softsimon** [comment]
I am aware of this. But Angular 2 is the latest stable release which the majority is using, and changing to <ng-template will lead to build fail for 2.x users. Not until 4.0 is released stable and people have upgraded this fix can be made.

**Comment by jiayihu** [comment]
Actually @softsimon it has been introduced in latest AOT commit https://github.com/softsimon/angular-2-dropdown-multiselect/blob/5c5176dc6d6955d8e3ca00f38cea5ec77a523333/src/multiselect-dropdown.ts#L127 and now I'm receive errors because I'm using Angular 2.X

**Comment by softsimon** [comment]
I am not sure how to handle this issue correctly. Support 2.x with deprecated warning for 4.x users or require 4.x? It would be unnecessary hassle with two branches.

**Comment by jiayihu** [comment]
I think since Angular 4 is just release as stable this lib should continue to support 2.x for a while and 4.x users will see a warning. [ng-bootstrap](https://github.com/ng-bootstrap/ng-bootstrap/issues/1337) is doing the same.

The problem with requiring 4.x is that then 2.x won't be able to use the lib because the application will throw instead of just logging a warning.
